//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/COPY000.pso /Fcshaderdump19/COPY000.pso.dis
//
//
// Parameters:
//
//   sampler2D Src0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Src0         texture_0       1
//

    float2 IN.texcoord_0 : TEXCOORD0;
    sampler2D Src0;
    OUT.color_0.rgba = tex2D(Src0, IN.texcoord_0);

// approximately 1 instruction slot used (1 texture, 0 arithmetic)
