//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/HAIR1000.pso /Fcshaderdump19/HAIR1000.pso.dis
//
//
// Parameters:
//
//   float4 AmbientColor;
//   sampler2D AnisoMap;
//   sampler2D DiffuseMap;
//   sampler2D NormalMap;
//   float4 PSLightColor[4];
//   float4 Toggles;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   AmbientColor AmbientColor       1
//   PSLightColor PSLightColor       1
//   Toggles      Toggles       1
//   DiffuseMap   DiffuseMap       1
//   NormalMap    NormalMap       1
//   AnisoMap     AnisoMap       1
//

    ps_1_3
    tex texcoord_0
    tex texcoord_1
    texm3x2pad texcoord_2, texcoord_1_bx2
    texm3x2tex texcoord_3, texcoord_1_bx2
    r0 = texcoord_3 * input_0.w;
    r1.xyz = r0.w * PSLightColor;
    r0.xyz = sat((PSLightColor * r0) + input_0);
    r0.xyz = sat(r0 - AmbientColor);
    r0.xyz = texcoord_0 * r0;
    mul_x2 r0.xyz, r0, Toggles
    r1.xyz = texcoord_1.w * r1;
  + r0.w = texcoord_0.w * AmbientColor.w;
    r0.xyz = (r1 * texcoord_0) + r0;

// approximately 12 instruction slots used (4 texture, 8 arithmetic)
