//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/NIGHTEYE000.pso /Fcshaderdump19/NIGHTEYE000.pso.dis
//
//
// Parameters:
//
//   float4 SpellInput;
//   sampler2D Src0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   SpellInput   const_1       1
//   Src0         texture_0       1
//

    const int4 const_0 = {1, 0, 0, -1};
    const float4 const_2 = {1, 1, 1, 0.5};
    const float4 const_3 = {0.21, 0.5, 0.78, 0};
    const int4 const_4 = {0, 0, 0, 1};
    IN.texcoord_0 = tex2D(s0, texcoord_0);
    r1 = dot(const_0, SpellInput);
    IN.texcoord_0.w = const_0.w + r1.w;
    IN.texcoord_0.w = IN.texcoord_0.w * IN.texcoord_0.w;
  + r1.xyz = dot(const_2, IN.texcoord_0);
    r0.w = (-IN.texcoord_0.w * const_2.w) + const_2.w;
    IN.texcoord_0.w = (r0.w > 0.5 ? const_4.w : const_3.w);
  + r1.xyz = r1 * const_3;
    r0.xyz = lerp(r1, IN.texcoord_0, IN.texcoord_0.w);
  + r0.w = const_4.w;

// approximately 7 instruction slots used (1 texture, 6 arithmetic)
