//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/PAR2021.pso /Fcshaderdump19/PAR2021.pso.dis
//
//
// Parameters:
//
//   sampler2D AttenuationMap;
//   sampler2D BaseMap;
//   sampler2D NormalMap;
//   float4 PSLightColor[4];
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   PSLightColor   const_2       3
//   NormalMap      NormalMap       1
//   BaseMap        BaseMap       1
//   AttenuationMap AttenuationMap       1
//

    const_0 = {0.0399999991, -0.0199999996, -0.5, 1};
    texcoord input_0.xy;
    texcoord input_1.xyz;			// centroid
    texcoord input_2.xyz;			// centroid
    texcoord input_3.xyz;			// centroid
    texcoord input_4;
    texcoord input_5;
    texcoord input_6;
    texcoord input_7.xyz;			// centroid
    sampler NormalMap;
    sampler BaseMap;
    sampler AttenuationMap;
    r0 = BaseMap[texcoord_0];			// partial precision
    r0.x = (texcoord_7.x * texcoord_7.x) + (texcoord_7.y * texcoord_7.y) + (texcoord_7.z * texcoord_7.z);			// partial precision
    r3.x = texcoord_5.z;
    r3.y = texcoord_5.w;
    r1.w = 1.0 / sqrt(r0.x);			// partial precision
    r0.xy = r1.w * texcoord_7;			// partial precision
    r0.w = (r0.w * const_0.x) - const_0.y;			// partial precision
    r2.xy = (r0.w * r0) + texcoord_0;
    r1.x = texcoord_4.z;
    r1.y = texcoord_4.w;
    r0.x = texcoord_6.z;
    r0.y = texcoord_6.w;
    r4 = AttenuationMap[r3];			// partial precision
    r5 = AttenuationMap[texcoord_5];			// partial precision
    r6 = NormalMap[r2];			// partial precision
    r2 = AttenuationMap[r1];			// partial precision
    r3 = AttenuationMap[texcoord_4];			// partial precision
    r0 = AttenuationMap[r0];			// partial precision
    r1 = AttenuationMap[texcoord_6];			// partial precision
    r6.xyz = r6 - const_0.z;
    r7.xyz = r6 - r6;			// partial precision
    r6.xyz = norm(r7);			// partial precision
    r7.xyz = norm(texcoord_2);			// partial precision
    r0.w = const_0.w - r5.x;			// partial precision
    r5.x = sat((r6.x * r7.x) + (r6.y * r7.y) + (r6.z * r7.z));			// partial precision
    r0.w = sat(r0.w - r4.x);			// partial precision
    r4.xyz = r5.x * const_3;			// partial precision
    r4.xyz = r0.w * r4;			// partial precision
    r5.xyz = norm(texcoord_1);			// partial precision
    r0.w = const_0.w - r3.x;			// partial precision
    r3.x = sat((r6.x * r5.x) + (r6.y * r5.y) + (r6.z * r5.z));			// partial precision
    r0.w = sat(r0.w - r2.x);			// partial precision
    r2.xyz = r3.x * const_2;			// partial precision
    r2.xyz = (r0.w * r2) + r4;			// partial precision
    r3.xyz = norm(texcoord_3);			// partial precision
    r0.w = const_0.w - r1.x;			// partial precision
    r1.x = sat((r6.x * r3.x) + (r6.y * r3.y) + (r6.z * r3.z));			// partial precision
    r0.w = sat(r0.w - r0.x);			// partial precision
    r0.xyz = r1.x * const_4;			// partial precision
    r0.xyz = (r0.w * r0) + r2;			// partial precision
    r0.w = const_0.w;
    rendertarget_0 = r0;			// partial precision

// approximately 50 instruction slots used (8 texture, 42 arithmetic)
