//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/PAR2024.pso /Fcshaderdump19/PAR2024.pso.dis
//
//
// Parameters:
//
//   sampler2D BaseMap;
//   sampler2D NormalMap;
//   float4 PSLightColor[4];
//   sampler2D ShadowMap;
//   sampler2D ShadowMaskMap;
//   float4 Toggles;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   PSLightColor[0]  const_2        1
//   Toggles       const_7       1
//   NormalMap     texture_0       1
//   BaseMap       texture_1       1
//   ShadowMap     texture_4       1
//   ShadowMaskMap texture_5       1
//

    const float4 const_0 = {0.04, -0.02, -0.5, 0.2};
    const int4 const_1 = {0, -1, 1, 0};
    float2 texcoord_0 : TEXCOORD0;
    float3 texcoord_1 : TEXCOORD1_centroid;			// partial precision
    float3 texcoord_3 : TEXCOORD3_centroid;			// partial precision
    float3 texcoord_7 : TEXCOORD7_centroid;			// partial precision
    float4 texcoord_6 : TEXCOORD6;			// partial precision
    sampler2D NormalMap;
    sampler2D BaseMap;
    sampler2D ShadowMap;
    sampler2D ShadowMaskMap;
    r0 = tex2D(BaseMap, IN.texcoord_0);			// partial precision
    r0.x = dot(IN.texcoord_7, IN.texcoord_7);			// partial precision
    r1.w = 1.0 / sqrt(r0.x);			// partial precision
    r0.xy = r1.w * IN.texcoord_7;			// partial precision
    r0.w = (r0.w * const_0.x) + const_0.y;			// partial precision
    r1.xy = (r0.w * r0) + IN.texcoord_0;			// partial precision
    r0.x = IN.texcoord_6.z;			// partial precision
    r0.y = IN.texcoord_6.w;			// partial precision
    r2 = tex2D(NormalMap, r1);			// partial precision
    r0 = tex2D(ShadowMaskMap, r0);			// partial precision
    r1 = tex2D(ShadowMap, IN.texcoord_6);			// partial precision
    r2.xyz = r2 + const_0.z;
    r3.xyz = r2 + r2;			// partial precision
    r2.xyz = normalize(r3);			// partial precision
    r3.xyz = normalize(IN.texcoord_3);			// partial precision
    r3.x = saturate(dot(r2, r3));			// partial precision
    r0.w = pow(abs(r3.x), Toggles.z);			// partial precision
    r3.xyz = normalize(IN.texcoord_1);			// partial precision
    r2.w = r2.w * r0.w;			// partial precision
    r2.x = dot(r2, r3);			// partial precision
    r3.w = r2.x - const_0.z;			// partial precision
    r0.w = const_0.w - r2.x;			// partial precision
    r1.w = max(r3.w, const_1.x);			// partial precision
    r1.w = r2.w * r1.w;			// partial precision
    r0.w = (r0.w >= 0.0 ? r2.w : r1.w);			// partial precision
    r2.xyz = r0.w * PSLightColor[0];			// partial precision
    r1.xyz = r1 + const_1.y;			// partial precision
    r0.xyz = (r0.x * r1) + const_1.z;			// partial precision
    r1.xyz = r2 * r0;			// partial precision
    r0.xyz = saturate(r1);			// partial precision
    r0.w = dot(r1, const_1.z);			// partial precision
    OUT.color_0 = r0;			// partial precision

// approximately 40 instruction slots used (4 texture, 36 arithmetic)
