//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/PAR2028.vso /Fcshaderdump19/PAR2028.vso.dis
//
//
// Parameters:
//
//   float4 EyePosition;
//   row_major float4x4 ModelViewProj;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   ModelViewProj[0] const_0        1
//   ModelViewProj[1] const_1        1
//   ModelViewProj[2] const_2        1
//   ModelViewProj[3] const_3        1
//   EyePosition   const_25      1
//

    float4 IN.position : POSITION;
    float3 IN.tangent : TANGENT;
    float3 IN.binormal : BINORMAL;
    float3 IN.normal : NORMAL;
    float4 IN.texcoord_0 : TEXCOORD0;
    float4 IN.color_0 : COLOR0;
    OUT.position.x = dot(ModelViewProj[0].xyzw, IN.position.xyzw);
    OUT.position.y = dot(ModelViewProj[1].xyzw, IN.position.xyzw);
    r1.xyz = EyePosition.xyz - IN.position.xyz;
    OUT.position.z = dot(ModelViewProj[2].xyzw, IN.position.xyzw);
    r0.xyz = normalize(r1.xyz);
    OUT.position.w = dot(ModelViewProj[3].xyzw, IN.position.xyzw);
    OUT.texcoord_6.x = dot(IN.tangent.xyz, r0.xyz);
    OUT.texcoord_6.y = dot(IN.binormal.xyz, r0.xyz);
    OUT.texcoord_6.z = dot(IN.normal.xyz, r0.xyz);
    OUT.texcoord_0.xy = IN.texcoord_0.xy;
    OUT.color_0.rgba = IN.color_0.rgba;

// approximately 13 instruction slots used
