//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SKIN2001.pso /Fcshaderdump19/SKIN2001.pso.dis
//
//
// Parameters:
//
//   float4 AmbientColor;
//   sampler2D BaseMap;
//   sampler2D FaceGenMap0;
//   sampler2D FaceGenMap1;
//   sampler2D NormalMap;
//   float4 PSLightColor[4];
//   sampler2D ShadowMap;
//   sampler2D ShadowMaskMap;
//   float4 Toggles;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   AmbientColor  AmbientColor       1
//   PSLightColor  PSLightColor       1
//   Toggles       Toggles       1
//   BaseMap       BaseMap       1
//   NormalMap     NormalMap       1
//   FaceGenMap0   FaceGenMap0       1
//   FaceGenMap1   FaceGenMap1       1
//   ShadowMap     ShadowMap       1
//   ShadowMaskMap ShadowMaskMap       1
//

    const_0 = {-0.5, 2, -1, 1};
    const_3 = {0, 0, 0, 0};
    texcoord input_0.xy;			// partial precision
    texcoord input_1.xyz;			// partial precision			// centroid
    texcoord input_6.xyz;			// partial precision			// centroid
    texcoord input_7;			// partial precision
    color input_0.xyz;
    color input_1;
    sampler BaseMap;
    sampler NormalMap;
    sampler FaceGenMap0;
    sampler FaceGenMap1;
    sampler ShadowMap;
    sampler ShadowMaskMap;
    r0 = NormalMap[texcoord_0];			// partial precision
    r0.xyz = r0 - const_0.x;
    r1.xyz = r0 - r0;			// partial precision
    r0.xyz = norm(r1);			// partial precision
    r1.xyz = norm(texcoord_6);			// partial precision
    r1.x = (r0.x * r1.x) + (r0.y * r1.y) + (r0.z * r1.z);			// partial precision
    r0.w = (r1.x >= const_3.x ? r1.x : const_3.x);			// partial precision
    r0.w = const_0.w - r0.w;			// partial precision
    r1.w = r0.w * r0.w;			// partial precision
    r1.x = (r0.x * texcoord_1.x) + (r0.y * texcoord_1.y) + (r0.z * texcoord_1.z);			// partial precision
    r0.w = r0.w * r1.w;			// partial precision
    r0.xyz = r0.w * PSLightColor;			// partial precision
    r0.xyz = r0 * -const_0.x;			// partial precision
    r0.w = (r1.x >= const_3.x ? r1.x : const_3.x);			// partial precision
    r5.xyz = (r0.w * PSLightColor) + r0;			// partial precision
    r0.x = texcoord_7.z;			// partial precision
    r0.y = texcoord_7.w;			// partial precision
    r3 = ShadowMaskMap[r0];			// partial precision
    r4 = ShadowMap[texcoord_7];			// partial precision
    r2 = FaceGenMap1[texcoord_0];			// partial precision
    r1 = FaceGenMap0[texcoord_0];			// partial precision
    r0 = BaseMap[texcoord_0];			// partial precision
    r4.xyz = r4 - const_0.z;			// partial precision
    r3.xyz = (r3.x * r4) - const_0.w;			// partial precision
    r4.xyz = (r3 * r5) + AmbientColor;			// partial precision
    r3.xyz = (r4 >= const_3.x ? r4 : const_3.x);			// partial precision
    r2.xyz = r2 - r2;			// partial precision
    r1.xyz = r1 - const_0.x;			// partial precision
    r0.xyz = (const_0.y * r1) - r0;			// partial precision
    r0.xyz = r2 * r0;			// partial precision
    r0.xyz = r0 - r0;			// partial precision
    r1.xyz = r0 * input_0;			// partial precision
    r0.xyz = (Toggles.x <= 0.0 ? r1 : r0);			// partial precision
    r1.xyz = (-r0 * r3) + input_1;			// partial precision
    r0.xyz = r3 * r0;			// partial precision
    r1.xyz = (input_1.w * r1) - r0;			// partial precision
    r0.w = r0.w * AmbientColor.w;			// partial precision
    r0.xyz = (Toggles.y <= 0.0 ? r1 : r0);			// partial precision
    rendertarget_0 = r0;			// partial precision

// approximately 43 instruction slots used (6 texture, 37 arithmetic)
