//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SKYTEXFADE.pso /Fcshaderdump19/SKYTEXFADE.pso.dis
//
//
// Parameters:
//
//   sampler2D TexMap;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   TexMap       TexMap       1
//

    texcoord input_0.xy;
    texcoord_2 input_1.x;
    color input_2;
    sampler TexMap;
    r0 = TexMap[input_0];
    r0.w = r0.w * input_2.w;
    rendertarget_0.xyz = r0 * input_2;
    rendertarget_0.w = r0.w * input_1.x;

// approximately 4 instruction slots used (1 texture, 3 arithmetic)
