//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SLS1030.pso /Fcshaderdump19/SLS1030.pso.dis
//
    float4 IN.color_0 : COLOR0;
    OUT.color_0.rgba = IN.color_0;

// approximately 1 instruction slot used
