//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SLS2040.vso /Fcshaderdump19/SLS2040.vso.dis
//
//
// Parameters:
//
//   float4 DecalFade[8];
//   row_major float4x4 DecalProjection[8];
//   row_major float4x4 ModelViewProj;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   ModelViewProj[0]   const_0        1
//   ModelViewProj[1]   const_1        1
//   ModelViewProj[2]   const_2        1
//   ModelViewProj[3]   const_3        1
//   DecalFade[0]       const_31       1
//   DecalFade[1]       const_32       1
//   DecalFade[2]       const_33       1
//   DecalFade[3]       const_34       1
//   DecalFade[4]       const_35       1
//   DecalFade[5]       const_36       1
//   DecalFade[6]       const_37       1
//   DecalFade[7]       const_38       1
//   DecalProjection[0][0] const_40         1
//   DecalProjection[0][1] const_41         1
//   DecalProjection[0][2] const_42         1
//   DecalProjection[0][3] const_43         1
//   DecalProjection[1][0] const_44         1
//   DecalProjection[1][1] const_45         1
//   DecalProjection[1][2] const_46         1
//   DecalProjection[1][3] const_47         1
//   DecalProjection[2][0] const_48        1
//   DecalProjection[2][1] const_49        1
//   DecalProjection[2][2] const_50        1
//   DecalProjection[2][3] const_51        1
//   DecalProjection[3][0] const_52        1
//   DecalProjection[3][1] const_53        1
//   DecalProjection[3][2] const_54        1
//   DecalProjection[3][3] const_55        1
//   DecalProjection[4][0] const_56       1
//   DecalProjection[4][1] const_57       1
//   DecalProjection[4][2] const_58       1
//   DecalProjection[4][3] const_59       1
//   DecalProjection[5][0] const_60      1
//   DecalProjection[5][1] const_61      1
//   DecalProjection[5][2] const_62      1
//   DecalProjection[5][3] const_63      1
//   DecalProjection[6][0] const_64      1
//   DecalProjection[6][1] const_65      1
//   DecalProjection[6][2] const_66      1
//   DecalProjection[6][3] const_67      1
//   DecalProjection[7][0] const_68      1
//   DecalProjection[7][1] const_69      1
//   DecalProjection[7][2] const_70      1
//   DecalProjection[7][3] const_71      1
//

    const float4 const_4 = {0.0125000002, 0.5, 0, 1};
    const float4 const_5 = {10, (1.0 / 256), 1, 0};
    float4 IN.position : POSITION;
    float3 IN.normal : NORMAL;
    OUT.position.x = dot(ModelViewProj[0].xyzw, IN.position.xyzw);
    OUT.position.y = dot(ModelViewProj[1].xyzw, IN.position.xyzw);
    OUT.position.z = dot(ModelViewProj[2].xyzw, IN.position.xyzw);
    r0.x = DecalProjection[0][0].w;
    r0.y = DecalProjection[0][1].w;
    r0.z = DecalProjection[0][2].w;
    OUT.position.w = dot(ModelViewProj[3].xyzw, IN.position.xyzw);
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[0][0].xyz, r0.xyz);
    r1.y = dot(DecalProjection[0][1].xyz, r0.xyz);
    r0.x = dot(DecalProjection[0][2].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[0][2].xyz);
    OUT.texcoord_0.xy = (0.0125000002 * r1.xy) + 0.5;
    r1.w = max(r2.x, 0);
    r0.w = abs(r0.x);
    r2.w = 1 - r1.w;
    r1.w = (r0.w * -(1.0 / 256)) + 1;
    r0.w = pow(abs(r2.w), 10);
    r0.w = r0.w * DecalFade[0].x;
    r0.x = DecalProjection[1][0].w;
    r0.y = DecalProjection[1][1].w;
    r0.z = DecalProjection[1][2].w;
    OUT.texcoord_0.z = r1.w * r0.w;
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[1][0].xyz, r0.xyz);
    r1.y = dot(DecalProjection[1][1].xyz, r0.xyz);
    r0.x = dot(DecalProjection[1][2].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[1][2].xyz);
    OUT.texcoord_1.xy = (0.0125000002 * r1.xy) + 0.5;
    r1.w = max(r2.x, 0);
    r0.w = abs(r0.x);
    r2.w = 1 - r1.w;
    r1.w = (r0.w * -(1.0 / 256)) + 1;
    r0.w = pow(abs(r2.w), 10);
    r0.w = r0.w * DecalFade[1].x;
    r0.x = DecalProjection[2][0].w;
    r0.y = DecalProjection[2][1].w;
    r0.z = DecalProjection[2][2].w;
    OUT.texcoord_1.z = r1.w * r0.w;
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[2][0].xyz, r0.xyz);
    r1.y = dot(DecalProjection[2][1].xyz, r0.xyz);
    r0.x = dot(DecalProjection[2][2].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[2][2].xyz);
    OUT.texcoord_2.xy = (0.0125000002 * r1.xy) + 0.5;
    r1.w = max(r2.x, 0);
    r0.w = abs(r0.x);
    r2.w = 1 - r1.w;
    r1.w = (r0.w * -(1.0 / 256)) + 1;
    r0.w = pow(abs(r2.w), 10);
    r0.w = r0.w * DecalFade[2].x;
    r0.x = DecalProjection[3][0].w;
    r0.y = DecalProjection[3][1].w;
    r0.z = DecalProjection[3][2].w;
    OUT.texcoord_2.z = r1.w * r0.w;
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[3][0].xyz, r0.xyz);
    r1.y = dot(DecalProjection[3][1].xyz, r0.xyz);
    r0.x = dot(DecalProjection[3][2].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[3][2].xyz);
    OUT.texcoord_3.xy = (0.0125000002 * r1.xy) + 0.5;
    r1.w = max(r2.x, 0);
    r0.w = abs(r0.x);
    r2.w = 1 - r1.w;
    r1.w = (r0.w * -(1.0 / 256)) + 1;
    r0.w = pow(abs(r2.w), 10);
    r0.w = r0.w * DecalFade[3].x;
    r0.x = DecalProjection[4][0].w;
    r0.y = DecalProjection[4][1].w;
    r0.z = DecalProjection[4][2].w;
    OUT.texcoord_3.z = r1.w * r0.w;
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[4][0].xyz, r0.xyz);
    r1.y = dot(DecalProjection[4][1].xyz, r0.xyz);
    r0.x = dot(DecalProjection[4][2].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[4][2].xyz);
    OUT.texcoord_4.xy = (0.0125000002 * r1.xy) + 0.5;
    r1.w = max(r2.x, 0);
    r0.w = abs(r0.x);
    r2.w = 1 - r1.w;
    r1.w = (r0.w * -(1.0 / 256)) + 1;
    r0.w = pow(abs(r2.w), 10);
    r0.w = r0.w * DecalFade[4].x;
    r0.x = DecalProjection[5][0].w;
    r0.y = DecalProjection[5][1].w;
    r0.z = DecalProjection[5][2].w;
    OUT.texcoord_4.z = r1.w * r0.w;
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[5][0].xyz, r0.xyz);
    r1.y = dot(DecalProjection[5][1].xyz, r0.xyz);
    r0.x = dot(DecalProjection[5][2].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[5][2].xyz);
    OUT.texcoord_5.xy = (0.0125000002 * r1.xy) + 0.5;
    r1.w = max(r2.x, 0);
    r0.w = abs(r0.x);
    r2.w = 1 - r1.w;
    r1.w = (r0.w * -(1.0 / 256)) + 1;
    r0.w = pow(abs(r2.w), 10);
    r0.w = r0.w * DecalFade[5].x;
    r0.x = DecalProjection[6][0].w;
    r0.y = DecalProjection[6][1].w;
    r0.z = DecalProjection[6][2].w;
    OUT.texcoord_5.z = r1.w * r0.w;
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[6][0].xyz, r0.xyz);
    r1.y = dot(DecalProjection[6][1].xyz, r0.xyz);
    r0.x = dot(DecalProjection[6][2].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[6][2].xyz);
    OUT.texcoord_6.xy = (0.0125000002 * r1.xy) + 0.5;
    r1.w = max(r2.x, 0);
    r0.w = abs(r0.x);
    r2.w = 1 - r1.w;
    r1.w = (r0.w * -(1.0 / 256)) + 1;
    r0.w = pow(abs(r2.w), 10);
    r0.w = r0.w * DecalFade[6].x;
    r0.x = DecalProjection[7][0].w;
    r0.y = DecalProjection[7][1].w;
    r0.z = DecalProjection[7][2].w;
    OUT.texcoord_6.z = r1.w * r0.w;
    r0.xyz = r0.xyz + IN.position.xyz;
    r1.x = dot(DecalProjection[7][0].xyz, r0.xyz);
    r2.x = dot(IN.normal.xyz, DecalProjection[7][2].xyz);
    r1.y = dot(DecalProjection[7][1].xyz, r0.xyz);
    r0.w = max(r2.x, 0);
    r0.x = dot(DecalProjection[7][2].xyz, r0.xyz);
    r2.w = 1 - r0.w;
    r1.w = abs(r0.x);
    r0.w = pow(abs(r2.w), 10);
    r1.w = (r1.w * -(1.0 / 256)) + 1;
    r0.w = r0.w * DecalFade[7].x;
    OUT.texcoord_7.xy = (0.0125000002 * r1.xy) + 0.5;
    OUT.texcoord_7.z = r1.w * r0.w;

// approximately 148 instruction slots used
