//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SLS2031.pso /Fcshaderdump19/SLS2031.pso.dis
//
//
// Parameters:
//
//   float4 AmbientColor;
//   sampler2D AttenuationMap;
//   sampler2D BaseMap;
//   sampler2D NormalMap;
//   float4 PSLightColor[4];
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   AmbientColor   AmbientColor       1
//   PSLightColor   const_2       3
//   BaseMap        BaseMap       1
//   NormalMap      NormalMap       1
//   AttenuationMap AttenuationMap       1
//

    const_0 = {-0.5, 1, 0, 0};
    texcoord input_0.xy;
    texcoord input_1.xyz;			// centroid
    texcoord input_2.xyz;			// centroid
    texcoord input_3.xyz;			// centroid
    texcoord input_4;
    texcoord input_5;
    sampler BaseMap;
    sampler NormalMap;
    sampler AttenuationMap;
    r1.x = texcoord_4.z;
    r1.y = texcoord_4.w;
    r0.x = texcoord_5.z;
    r0.y = texcoord_5.w;
    r3 = AttenuationMap[r1];			// partial precision
    r4 = AttenuationMap[texcoord_4];			// partial precision
    r5 = NormalMap[texcoord_0];			// partial precision
    r1 = AttenuationMap[r0];			// partial precision
    r2 = AttenuationMap[texcoord_5];			// partial precision
    r0 = BaseMap[texcoord_0];			// partial precision
    r6.xyz = norm(texcoord_2);			// partial precision
    r0.xyz = r5 - const_0.x;
    r5.xyz = r0 - r0;			// partial precision
    r0.xyz = norm(r5);			// partial precision
    r1.w = const_0.y - r4.x;			// partial precision
    r4.x = sat((r0.x * r6.x) + (r0.y * r6.y) + (r0.z * r6.z));			// partial precision
    r1.w = sat(r1.w - r3.x);			// partial precision
    r3.xyz = r4.x * const_3;			// partial precision
    r3.xyz = r1.w * r3;			// partial precision
    r4.x = sat((r0.x * texcoord_1.x) + (r0.y * texcoord_1.y) + (r0.z * texcoord_1.z));			// partial precision
    r3.xyz = (r4.x * const_2) + r3;			// partial precision
    r4.xyz = norm(texcoord_3);			// partial precision
    r1.w = const_0.y - r2.x;			// partial precision
    r0.x = sat((r0.x * r4.x) + (r0.y * r4.y) + (r0.z * r4.z));			// partial precision
    r1.w = sat(r1.w - r1.x);			// partial precision
    r0.xyz = r0.x * const_4;			// partial precision
    r0.xyz = (r1.w * r0) + r3;			// partial precision
    r0.xyz = r0 - AmbientColor;			// partial precision
    rendertarget_0 = r0;			// partial precision

// approximately 35 instruction slots used (6 texture, 29 arithmetic)
