//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SM3021.pso /Fcshaderdump19/SM3021.pso.dis
//
//
// Parameters:
//
//   samplerCUBE EnvironmentCubeMap;
//   float4 MatAlpha;
//   sampler2D NormalMap;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   MatAlpha           const_3       1
//   NormalMap          texture_0       1
//   EnvironmentCubeMap texture_1       1
//

    const float4 const_0 = {-0.5, 0.5, 1, 0};
    float2 IN.texcoord_0 : TEXCOORD0;			// partial precision
    float4 input_1 : TEXCOORD1_centroid;			// partial precision
    float4 input_2 : TEXCOORD2_centroid;			// partial precision
    float4 input_3 : TEXCOORD3_centroid;			// partial precision
    float3 IN.color_0 : COLOR0;			// partial precision
    sampler2D NormalMap;
    samplerCUBE EnvironmentCubeMap;
    r1 = tex2D(NormalMap, IN.texcoord_0);			// partial precision
    r0.xyz = r1 + -0.5;
    r1.xyz = r0 + r0;			// partial precision
    r0.xyz = normalize(r1);			// partial precision
    r2.xyz = r0 * const_0.yyzw;			// partial precision
    r1.xyz = normalize(IN.input_1);			// partial precision
    r0.xyz = normalize(r2);			// partial precision
    r1.x = dot(r0, r1);			// partial precision
    r2.xyz = normalize(IN.input_2);			// partial precision
    r1.y = dot(r0, r2);			// partial precision
    r2.xyz = normalize(IN.input_3);			// partial precision
    r1.z = dot(r0, r2);			// partial precision
    r2.x = IN.input_1.w;			// partial precision
    r2.y = IN.input_2.w;			// partial precision
    r2.z = IN.input_3.w;			// partial precision
    r0.xyz = normalize(r1);			// partial precision
    r1.xyz = normalize(r2);			// partial precision
    r0.w = dot(r0, r1);			// partial precision
    r2.w = dot(r0, r0);	// normalize + length			// partial precision
    r0.w = r0.w + r0.w;			// partial precision
    r1.xyz = r1 * r2.w;			// partial precision
    r0.xyz = (r0.w * r0) - r1;			// partial precision
    r0 = texCUBE(EnvironmentCubeMap, r0);			// partial precision
    r0.xyz = r1.w * r0;			// partial precision
    r0.xyz = r0 * MatAlpha.x;			// partial precision
    OUT.color_0.rgb = r0 * IN.color_0;			// partial precision
    OUT.color_0.a = 1;			// partial precision

// approximately 41 instruction slots used (2 texture, 39 arithmetic)
