//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SM3026.vso /Fcshaderdump19/SM3026.vso.dis
//
//
// Parameters:
//
//   float4 Bones[54];
//   row_major float4x4 SkinModelViewProj;
//   row_major float4x4 SkinWorldViewTranspose;
//
//
// Registers:
//
//   Name                   Reg   Size
//   ---------------------- ----- ----
//   SkinModelViewProj[0]      const_1        1
//   SkinModelViewProj[1]      const_2        1
//   SkinModelViewProj[2]      const_3        1
//   SkinModelViewProj[3]      const_4        1
//   SkinWorldViewTranspose[0] const_6        1
//   SkinWorldViewTranspose[1] const_7        1
//   SkinWorldViewTranspose[2] const_8        1
//   Bones[0]                  const_31      18
//   Bones[1]                  const_32      18
//   Bones[2]                  const_33      18
//

    const float4 const_0 = {1, 765.01001, 0, 0.5};
    const float4 const_5 = {5, -4.4, 0, 0};
    float4 IN.position : POSITION;
    float3 IN.normal : NORMAL;
    float3 IN.blendweight : BLENDWEIGHT;
    float4 IN.blendindices : BLENDINDICES;
    float4 OUT.position : POSITION;
    float3 OUT.texcoord_0 : TEXCOORD0;
    float OUT.texcoord_1 : TEXCOORD1;
    r1 = const_0.y * IN.blendindices.zyxw;
    r0 = r1 - floor(r1);
    r2.w = dot(IN.blendweight, const_0.x);
    r0 = r1 - r0;
    offset = r0;
    r0 = (IN.position.xyzx * const_0.xxxz) + const_0.zzzx;
    r1.w = const_0.x - r2.w;
    r1.x = dot(Bones[0 + offset.y], r0);
    r1.y = dot(Bones[1 + offset.y], r0);
    r1.z = dot(Bones[2 + offset.y], r0);
    r2.xyz = r1 * IN.blendweight.y;
    r1.x = dot(Bones[0 + offset.x], r0);
    r1.y = dot(Bones[1 + offset.x], r0);
    r1.z = dot(Bones[2 + offset.x], r0);
    r2.xyz = (IN.blendweight.x * r1) + r2;
    r1.x = dot(Bones[0 + offset.z], r0);
    r1.y = dot(Bones[1 + offset.z], r0);
    r1.z = dot(Bones[2 + offset.z], r0);
    r2.xyz = (IN.blendweight.z * r1) + r2;
    r1.x = dot(Bones[0 + offset.w], r0);
    r1.y = dot(Bones[1 + offset.w], r0);
    r1.z = dot(Bones[2 + offset.w], r0);
    r0.xyz = (r1.w * r1) + r2;
    r0.w = const_0.x;
    r1.x = dot(Bones[0 + offset.y], IN.normal);
    r1.y = dot(Bones[1 + offset.y], IN.normal);
    r1.z = dot(Bones[2 + offset.y], IN.normal);
    r2.xyz = r1 * IN.blendweight.y;
    r1.x = dot(Bones[0 + offset.x], IN.normal);
    r1.y = dot(Bones[1 + offset.x], IN.normal);
    r1.z = dot(Bones[2 + offset.x], IN.normal);
    r2.xyz = (IN.blendweight.x * r1) + r2;
    r1.x = dot(Bones[0 + offset.z], IN.normal);
    r1.y = dot(Bones[1 + offset.z], IN.normal);
    r1.z = dot(Bones[2 + offset.z], IN.normal);
    r2.xyz = (IN.blendweight.z * r1) + r2;
    r1.x = dot(Bones[0 + offset.w], IN.normal);
    r1.y = dot(Bones[1 + offset.w], IN.normal);
    r1.z = dot(Bones[2 + offset.w], IN.normal);
    OUT.position.x = dot(SkinModelViewProj[0], r0);
    r1.xyz = (r1.w * r1) + r2;
    OUT.position.y = dot(SkinModelViewProj[1], r0);
    r2.xyz = normalize(r1);
    OUT.position.w = dot(SkinModelViewProj[3], r0);
    r1.x = dot(SkinWorldViewTranspose[0], r2);
    r1.y = dot(SkinWorldViewTranspose[1], r2);
    r1.z = dot(SkinWorldViewTranspose[2], r2);
    r0.y = dot(SkinModelViewProj[2], r0);
    OUT.texcoord_0.xyz = (const_0.w * r1) + const_0.w;
    OUT.texcoord_1.x = (r0.y * const_5.x) + const_5.y;
    OUT.position.z = r0.y;

// approximately 53 instruction slots used
