//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SM3018.vso /Fcshaderdump19/SM3018.vso.dis
//
//
// Parameters:
//
//   row_major float4x4 ModelViewProj;
//   row_major float4x4 WorldView;
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   ModelViewProj[0] const_0        1
//   ModelViewProj[1] const_1        1
//   ModelViewProj[2] const_2        1
//   ModelViewProj[3] const_3        1
//   WorldView[0]     const_5        1
//   WorldView[1]     const_6        1
//   WorldView[2]     const_7        1
//

    const int4 const_4 = {0, 0, 0, 0};
    float4 IN.position : POSITION;
    float4 IN.texcoord_0 : TEXCOORD0;
    float4 OUT.position : POSITION;
    float2 OUT.texcoord_0 : TEXCOORD0;
    float4 OUT.texcoord_1 : TEXCOORD1;
    OUT.position.x = dot(ModelViewProj[0], IN.position);
    OUT.position.y = dot(ModelViewProj[1], IN.position);
    OUT.position.z = dot(ModelViewProj[2], IN.position);
    OUT.position.w = dot(ModelViewProj[3], IN.position);
    OUT.texcoord_1.x = dot(WorldView[0], IN.position);
    OUT.texcoord_1.y = dot(WorldView[1], IN.position);
    OUT.texcoord_1.z = dot(WorldView[2], IN.position);
    OUT.texcoord_0.xy = IN.texcoord_0;
    OUT.texcoord_1.w = 0;

// approximately 9 instruction slots used
