//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SM3037.pso /Fcshaderdump19/SM3037.pso.dis
//
    const int4 const_0 = {0, 0, 0, 0};
    OUT.color_0.rgba = 0;			// partial precision

// approximately 1 instruction slot used
