//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SM3012.vso /Fcshaderdump19/SM3012.vso.dis
//
//
// Parameters:
//
//   float3 BoundWorldCenter;
//   float3 EyePosition;
//   row_major float4x4 ModelViewProj;
//   row_major float4x4 ObjToCubeSpace;
//
//
// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   ModelViewProj[0]    const_0        1
//   ModelViewProj[1]    const_1        1
//   ModelViewProj[2]    const_2        1
//   ModelViewProj[3]    const_3        1
//   ObjToCubeSpace[0]   const_10       1
//   ObjToCubeSpace[1]   const_11       1
//   ObjToCubeSpace[2]   const_12       1
//   EyePosition      const_14      1
//   BoundWorldCenter const_20      1
//

    const int4 const_4 = {-2, 3, 0, 0};
    const float4 const_5 = {0.5, -0.8, 6.66666651, 1};
    float4 IN.position : POSITION;
    float4 IN.texcoord_0 : TEXCOORD0;
    float4 OUT.position : POSITION;
    float2 OUT.texcoord_0 : TEXCOORD0;
    float4 OUT.texcoord_1 : TEXCOORD1;
    float3 OUT.texcoord_2 : TEXCOORD2;
    float3 OUT.color_0 : COLOR0;
    OUT.position.x = dot(ModelViewProj[0], IN.position);
    OUT.position.y = dot(ModelViewProj[1], IN.position);
    r0.x = dot(ObjToCubeSpace[0], IN.position);
    r0.y = dot(ObjToCubeSpace[1], IN.position);
    r0.z = dot(ObjToCubeSpace[2], IN.position);
    OUT.position.z = dot(ModelViewProj[2], IN.position);
    r2.xyz = r0 - BoundWorldCenter;
    r0.xyz = EyePosition - r0;
    r1.xyz = normalize(r2);
    r2.xyz = normalize(r0);
    r1.w = dot(r1, r1);	// normalize + length
    r0.w = dot(r1, r2);
    r1.w = 1.0 / sqrt(r1.w);
    OUT.position.w = dot(ModelViewProj[3], IN.position);
    r0.w = (r0.w * r1.w) + const_5.y;
    OUT.texcoord_1.xyz = (const_5.x * r1) + const_5.x;
    r1.w = saturate(r0.w * const_5.z);
    r0.w = (r1.w * const_4.x) + const_4.y;
    r1.w = r1.w * r1.w;
    OUT.texcoord_2.xyz = r0;
    OUT.texcoord_1.w = r0.w * r1.w;
    OUT.texcoord_0.xy = IN.texcoord_0;
    OUT.color_0.rgb = const_5.w;

// approximately 27 instruction slots used
