//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SM3022.pso /Fcshaderdump19/SM3022.pso.dis
//
//
// Parameters:
//
//   samplerCUBE EnvironmentCubeMap;
//   float4 MatAlpha;
//   sampler2D NormalMap;
//   float4 PSLightColor;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   MatAlpha           MatAlpha       1
//   PSLightColor       PSLightColor       1
//   NormalMap          NormalMap       1
//   EnvironmentCubeMap EnvironmentCubeMap       1
//

    const_0 = {-0.5, 1, 0, 0};
    texcoord input_0.xy;			// partial precision
    texcoord_1 input_1;			// partial precision			// centroid
    texcoord_2 input_2.xyz;			// partial precision			// centroid
    color input_3.xyz;			// partial precision
    sampler NormalMap;
    dcl_cube EnvironmentCubeMap
    r0.xyz = input_1 - const_0.x;
    r0.xyz = r0 - r0;			// partial precision
    r1.xyz = norm(input_2);			// partial precision
    r0.w = (r0.x * r1.x) + (r0.y * r1.y) + (r0.z * r1.z);			// partial precision
    r1.w = (r0.x * r0.x) + (r0.y * r0.y) + (r0.z * r0.z);			// partial precision
    r0.w = r0.w - r0.w;			// partial precision
    r1.xyz = r1 * r1.w;			// partial precision
    r0.xyz = (r0.w * r0) - r1;			// partial precision
    r0 = EnvironmentCubeMap[r0];			// partial precision
    r1 = NormalMap[input_0];			// partial precision
    r0.xyz = r0 * r1.w;			// partial precision
    r0.xyz = r0 * MatAlpha.x;			// partial precision
    r0.xyz = r0 * input_3;			// partial precision
    r0.xyz = r0 * PSLightColor;			// partial precision
    rendertarget_0.xyz = r0 * input_1.w;			// partial precision
    rendertarget_0.w = const_0.y;			// partial precision

// approximately 18 instruction slots used (2 texture, 16 arithmetic)
