//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SM3LL000.pso /Fcshaderdump19/SM3LL000.pso.dis
//
//
// Parameters:
//
//   float4 AmbientColor;
//   sampler2D BaseMap;
//   float4 LightData[8];
//   float3 MatAlpha;
//   sampler2D NormalMap;
//   float4 ToggleADTS;
//   float4 ToggleNumLights;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   AmbientColor    AmbientColor       1
//   MatAlpha        MatAlpha       1
//   ToggleADTS      ToggleADTS       1
//   ToggleNumLights ToggleNumLights       1
//   LightData[0]       LightData[0]       1
//   LightData[1]       LightData[1]      1
//   LightData[2]       LightData[2]      1
//   LightData[3]       LightData[3]      1
//   LightData[4]       LightData[4]      1
//   LightData[5]       LightData[5]      1
//   LightData[6]       LightData[6]      1
//   LightData[7]       LightData[7]      1
//   BaseMap         BaseMap       1
//   NormalMap       NormalMap       1
//

    const_1 = {-0.5, 0, 1, 4};
    const_2 = {2, -4, -5, -6};
    const_4 = {2, -6, -7, 0};
    const_7 = {-1, -2, 0, 2};
    const_8 = {2, -2, -3, -4};
    texcoord input_0.xy;			// partial precision
    color input_1.xyz;			// partial precision
    texcoord_3 input_2.xyz;			// partial precision			// centroid
    texcoord_4 input_3.xyz;			// partial precision			// centroid
    texcoord_5 input_4.xyz;			// partial precision			// centroid
    texcoord_6 input_5.xyz;			// partial precision			// centroid
    texcoord_7 input_6;			// partial precision			// centroid
    sampler BaseMap;
    sampler NormalMap;
    r2.yzw = const_1;
    r0.w = r2.w - ToggleNumLights.x;			// partial precision
    r1.x = (ToggleNumLights.y < r0.w ? ToggleNumLights.y : r0.w);			// partial precision
    r1.w = r1.x - floor(r1.x);			// partial precision
    r1.z = (r1.x >= 0.0 ? const_1.z : const_1.y);
    r1.y = (r1.w <= 0.0 ? const_1.z : const_1.y);
    r0 = NormalMap[input_0];			// partial precision
    r0.xyz = r0 - const_1.x;			// partial precision
    r0.xyz = r0 - r0;			// partial precision
    r4.xyz = norm(input_2);			// partial precision
    r3.xyz = norm(r0);			// partial precision
    r0.x = (r4.x * LightData[1].x) + (r4.y * LightData[1].y) + (r4.z * LightData[1].z);			// partial precision
    r6.xyz = norm(input_3);			// partial precision
    r5.xyz = norm(input_4);			// partial precision
    r0.y = (r6.x * LightData[1].x) + (r6.y * LightData[1].y) + (r6.z * LightData[1].z);			// partial precision
    r0.z = (r5.x * LightData[1].x) + (r5.y * LightData[1].y) + (r5.z * LightData[1].z);			// partial precision
    r0.w = r1.x - r1.w;			// partial precision
    r1.w = (r3.x * r0.x) + (r3.y * r0.y) + (r3.z * r0.z);			// partial precision
    r2.w = (r1.z * r1.y) - r0.w;
    r0.z = (r1.w >= const_1.y ? r1.w : const_1.y);			// partial precision
    r0.w = const_1.z;
    r0.xyz = r0.z * LightData[0];			// partial precision
    r0 = (ToggleNumLights.x <= 0.0 ? r0 : r2.y);
    r1.w = (r2.w <= 0.0 ? const_1.z : const_1.y);
    if_ne r1.w, -r1.w
      r7.x = r0.w - r0.w;
      r7.yz = r7.x - const_7.xxyw;
      r1.xyz = r7.x - const_7.zxyw;
      r7.xyz = (r1 >= 0.0 ? -r7 : r1);
      r1 = (r7.x <= 0.0 ? r2.y : LightData[1]);
      r1 = (r7.y <= 0.0 ? r1 : LightData[2]);
      r1 = (r7.z <= 0.0 ? r1 : LightData[3]);
      r8.xyz = r1 - input_5;
      r1.z = (r8.x * r8.x) + (r8.y * r8.y) + (r8.z * r8.z);
      r2.x = 1.0 / sqrt(r1.z);
      r1.xyz = (r7.x <= 0.0 ? r2.y : LightData[0]);			// partial precision
      r2.x = 1.0 / r2.x;
      r1.w = 1.0 / r1.w;			// partial precision
      r9.x = (r4.x * r8.x) + (r4.y * r8.y) + (r4.z * r8.z);
      r9.y = (r6.x * r8.x) + (r6.y * r8.y) + (r6.z * r8.z);
      r9.z = (r5.x * r8.x) + (r5.y * r8.y) + (r5.z * r8.z);
      r2.x = sat(r2.x * r1.w);
      r8.xyz = norm(r9);			// partial precision
      r1.w = (r3.x * r8.x) + (r3.y * r8.y) + (r3.z * r8.z);			// partial precision
      r2.x = (r2.x * -r2.x) - const_1.z;			// partial precision
      r1.xyz = (r7.y <= 0.0 ? r1 : LightData[1]);			// partial precision
      r2.x = r1.w * r2.x;			// partial precision
      r1.xyz = (r7.z <= 0.0 ? r1 : LightData[2]);			// partial precision
      r1.w = (r2.x >= const_1.y ? r2.x : const_1.y);			// partial precision
      r0.xyz = (r1.w * r1) + r0;			// partial precision
      r0.w = r0.w - const_1.z;
    endif
    if_lt const_1.z, r2.w
      r7.xyz = (const_8.x * r0.w) - const_8.yzww;
      r1 = (r7.x == 0.0 ? LightData[3] : r2.y)
      r1 = (r7.y == 0.0 ? LightData[4] : r1)
      r1 = (r7.z == 0.0 ? LightData[5] : r1)
      r8.xyz = r1 - input_5;
      r1.z = (r8.x * r8.x) + (r8.y * r8.y) + (r8.z * r8.z);
      r2.x = 1.0 / sqrt(r1.z);
      r1.xyz = (r7.x == 0.0 ? LightData[2] : r2.y)			// partial precision
      r2.x = 1.0 / r2.x;
      r1.w = 1.0 / r1.w;			// partial precision
      r9.x = (r4.x * r8.x) + (r4.y * r8.y) + (r4.z * r8.z);
      r9.y = (r6.x * r8.x) + (r6.y * r8.y) + (r6.z * r8.z);
      r9.z = (r5.x * r8.x) + (r5.y * r8.y) + (r5.z * r8.z);
      r2.x = sat(r2.x * r1.w);
      r8.xyz = norm(r9);			// partial precision
      r1.w = (r3.x * r8.x) + (r3.y * r8.y) + (r3.z * r8.z);			// partial precision
      r2.x = (r2.x * -r2.x) - const_1.z;			// partial precision
      r1.xyz = (r7.y == 0.0 ? LightData[3] : r1)			// partial precision
      r2.x = r1.w * r2.x;			// partial precision
      r1.xyz = (r7.z == 0.0 ? LightData[4] : r1)			// partial precision
      r1.w = (r2.x >= const_1.y ? r2.x : const_1.y);			// partial precision
      r1.xyz = (r1.w * r1) + r0;			// partial precision
      r1.w = r0.w - const_1.z;
    else
      r1.xyz = r0;			// partial precision
      r1.w = r0.w;
    endif
    if_lt const_7.w, r2.w
      r7.xyz = (const_2.x * r1.w) - const_2.yzww;
      r0 = (r7.x == 0.0 ? LightData[5] : r2.y)
      r0 = (r7.y == 0.0 ? LightData[6] : r0)
      r0 = (r7.z == 0.0 ? LightData[7] : r0)
      r8.xyz = r0 - input_5;
      r0.z = (r8.x * r8.x) + (r8.y * r8.y) + (r8.z * r8.z);
      r2.x = 1.0 / sqrt(r0.z);
      r0.xyz = (r7.x == 0.0 ? LightData[4] : r2.y)			// partial precision
      r2.x = 1.0 / r2.x;
      r0.w = 1.0 / r0.w;			// partial precision
      r9.x = (r4.x * r8.x) + (r4.y * r8.y) + (r4.z * r8.z);
      r9.y = (r6.x * r8.x) + (r6.y * r8.y) + (r6.z * r8.z);
      r9.z = (r5.x * r8.x) + (r5.y * r8.y) + (r5.z * r8.z);
      r2.x = sat(r2.x * r0.w);
      r8.xyz = norm(r9);			// partial precision
      r0.w = (r3.x * r8.x) + (r3.y * r8.y) + (r3.z * r8.z);			// partial precision
      r2.x = (r2.x * -r2.x) - const_1.z;			// partial precision
      r0.xyz = (r7.y == 0.0 ? LightData[5] : r0)			// partial precision
      r2.x = r0.w * r2.x;			// partial precision
      r0.xyz = (r7.z == 0.0 ? LightData[6] : r0)			// partial precision
      r0.w = (r2.x >= const_1.y ? r2.x : const_1.y);			// partial precision
      r1.xyz = (r0.w * r0) + r1;			// partial precision
      r1.w = r1.w - const_1.z;
    endif
    if_lt -const_8.z, r2.w
      r0.xyz = LightData[7] - input_5;
      r4.x = (r4.x * r0.x) + (r4.y * r0.y) + (r4.z * r0.z);
      r4.y = (r6.x * r0.x) + (r6.y * r0.y) + (r6.z * r0.z);
      r4.z = (r5.x * r0.x) + (r5.y * r0.y) + (r5.z * r0.z);
      r0.w = (r0.x * r0.x) + (r0.y * r0.y) + (r0.z * r0.z);
      r0.xyz = norm(r4);			// partial precision
      r0.w = 1.0 / sqrt(r0.w);
      r2.w = 1.0 / r0.w;
      r2.x = 1.0 / LightData[7].w;
      r0.w = (r3.x * r0.x) + (r3.y * r0.y) + (r3.z * r0.z);			// partial precision
      r0.z = sat(r2.w * r2.x);
      r0.z = (r0.z * -r0.z) - const_1.z;			// partial precision
      r3.xy = (const_4.x * r1.w) - const_4.yzzw;
      r1.w = r0.w * r0.z;			// partial precision
      r0.xyz = (r3.x == 0.0 ? LightData[6] : r2.y)			// partial precision
      r0.w = (r1.w >= const_1.y ? r1.w : const_1.y);			// partial precision
      r0.xyz = (r3.y == 0.0 ? LightData[7] : r0)			// partial precision
      r1.xyz = (r0.w * r0) + r1;			// partial precision
    endif
    r0.z = r2.z - ToggleADTS.x;			// partial precision
    r0.w = ToggleADTS.x;			// partial precision
    r0.xyz = (r0.w * AmbientColor) + r0.z;			// partial precision
    r1.xyz = r1 - r0;			// partial precision
    r0 = BaseMap[input_0];			// partial precision
    r0.xyz = r0 * input_1;			// partial precision
    r1.xyz = r1 * r0;			// partial precision
    r0.xyz = input_6 - r1;			// partial precision
    rendertarget_0.xyz = (input_6.w * r0) - r1;			// partial precision
    rendertarget_0.w = r0.w * MatAlpha.x;			// partial precision

// approximately 151 instruction slots used (2 texture, 149 arithmetic)
