//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SM3LL005.pso /Fcshaderdump19/SM3LL005.pso.dis
//
//
// Parameters:
//
//   float4 AmbientColor;
//   sampler2D BaseMap;
//   float3 EyePosition;
//   float4 LightData[8];
//   float3 MatAlpha;
//   sampler2D NormalMap;
//   float4 ToggleADTS;
//   float4 ToggleNumLights;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   AmbientColor    AmbientColor       1
//   EyePosition     EyePosition       1
//   MatAlpha        MatAlpha       1
//   ToggleADTS      ToggleADTS       1
//   ToggleNumLights ToggleNumLights       1
//   LightData[0]       LightData[0]       1
//   LightData[1]       LightData[1]      1
//   LightData[2]       LightData[2]      1
//   LightData[3]       LightData[3]      1
//   LightData[4]       LightData[4]      1
//   LightData[5]       LightData[5]      1
//   LightData[6]       LightData[6]      1
//   LightData[7]       LightData[7]      1
//   BaseMap         BaseMap       1
//   NormalMap       NormalMap       1
//

    const_2 = {0.0399999991, -0.0199999996, -0.5, 0};
    const_4 = {0, 1, 4, 2};
    const_7 = {2, -2, -3, -4};
    const_8 = {2, -6, -7, 0};
    EyePosition7 = {2, -4, -5, -6};
    texcoord input_0.xy;			// partial precision
    color input_1.xyz;			// partial precision
    texcoord_3 input_2.xyz;			// partial precision			// centroid
    texcoord_4 input_3.xyz;			// partial precision			// centroid
    texcoord_5 input_4.xyz;			// partial precision			// centroid
    texcoord_6 input_5.xyz;			// partial precision			// centroid
    texcoord_7 input_6;			// partial precision			// centroid
    sampler BaseMap;
    sampler NormalMap;
    r0 = BaseMap[input_0];			// partial precision
    r7.xyz = norm(input_4);			// partial precision
    r1.xyz = EyePosition - input_5;			// partial precision
    r0.z = (r7.x * r1.x) + (r7.y * r1.y) + (r7.z * r1.z);			// partial precision
    r9.xyz = norm(input_2);			// partial precision
    r8.xyz = norm(input_3);			// partial precision
    r0.x = (r9.x * r1.x) + (r9.y * r1.y) + (r9.z * r1.z);			// partial precision
    r0.y = (r8.x * r1.x) + (r8.y * r1.y) + (r8.z * r1.z);			// partial precision
    r0.w = (r0.w * const_2.x) - const_2.y;			// partial precision
    r6.xyz = norm(r0);			// partial precision
    r12.xy = (r0.w * r6) + input_0;			// partial precision
    r0 = NormalMap[r12];
    r0 = r0 - const_2.z;
    r0 = r0 - r0;			// partial precision
    r3.xyz = const_4;
    r1.w = (ToggleNumLights.x <= 0.0 ? r3.y : r3.x);
    r4.xyz = norm(r0);			// partial precision
    if_ne r1.w, -r1.w
      r0.x = (r9.x * LightData[1].x) + (r9.y * LightData[1].y) + (r9.z * LightData[1].z);			// partial precision
      r0.y = (r8.x * LightData[1].x) + (r8.y * LightData[1].y) + (r8.z * LightData[1].z);			// partial precision
      r0.z = (r7.x * LightData[1].x) + (r7.y * LightData[1].y) + (r7.z * LightData[1].z);			// partial precision
      r2.xyz = r6 - r0;			// partial precision
      r1.xyz = norm(r2);			// partial precision
      r1.z = sat((r1.x * r4.x) + (r1.y * r4.y) + (r1.z * r4.z));			// partial precision
      r1.w = (r4.x * r0.x) + (r4.y * r0.y) + (r4.z * r0.z);			// partial precision
      pow r0.z, r1.z, ToggleNumLights.z			// partial precision
      r0.y = (r1.w >= const_2.w ? r1.w : const_2.w);			// partial precision
      r3.w = const_4.y;
      r2.xyz = r0.y * LightData[0];			// partial precision
      r0.xyz = r0.z * LightData[0];			// partial precision
    else
      r1.w = const_2.w;
      r2.xyz = r1.w;			// partial precision
      r0.xyz = r1.w;			// partial precision
      r3.w = r1.w;
    endif
    r2.w = r3.z - ToggleNumLights.x;			// partial precision
    r1.x = (ToggleNumLights.y < r2.w ? ToggleNumLights.y : r2.w);			// partial precision
    r1.w = (r1.x >= 0.0 ? const_4.y : const_4.x);
    r1.y = r1.x - floor(r1.x);			// partial precision
    r1.z = (r1.y <= 0.0 ? const_4.y : const_4.x);
    r1.y = r1.x - r1.y;			// partial precision
    r2.w = (r1.w * r1.z) - r1.y;
    r1.w = (r2.w <= 0.0 ? const_4.y : const_4.x);
    if_ne r1.w, -r1.w
      r5.x = r3.w - r3.w;
      r5.yz = r5.x - const_4.xyww;
      r1.xyz = r5.x - const_4.xyww;
      r10.xyz = (r1 >= 0.0 ? -r5 : r1);
      r3.x = const_2.w;
      r1 = (r10.x <= 0.0 ? r3.x : LightData[1]);
      r1 = (r10.y <= 0.0 ? r1 : LightData[2]);
      r1 = (r10.z <= 0.0 ? r1 : LightData[3]);
      r11.xyz = (r10.x <= 0.0 ? r3.x : LightData[0]);			// partial precision
      r5.xyz = r1 - input_5;
      r1.xyz = (r10.y <= 0.0 ? r11 : LightData[1]);			// partial precision
      r11.x = (r9.x * r5.x) + (r9.y * r5.y) + (r9.z * r5.z);
      r11.y = (r8.x * r5.x) + (r8.y * r5.y) + (r8.z * r5.z);
      r11.z = (r7.x * r5.x) + (r7.y * r5.y) + (r7.z * r5.z);
      r1.xyz = (r10.z <= 0.0 ? r1 : LightData[2]);			// partial precision
      r10.xyz = norm(r11);			// partial precision
      r3.z = (r5.x * r5.x) + (r5.y * r5.y) + (r5.z * r5.z);
      r11.xyz = r6 - r10;			// partial precision
      r3.z = 1.0 / sqrt(r3.z);
      r5.xyz = norm(r11);			// partial precision
      r3.x = 1.0 / r3.z;
      r4.w = sat((r5.x * r4.x) + (r5.y * r4.y) + (r5.z * r4.z));			// partial precision
      r1.w = 1.0 / r1.w;			// partial precision
      pow r3.z, r4.w, ToggleNumLights.z			// partial precision
      r1.w = sat(r3.x * r1.w);
      r5.xyz = r1 * r3.z;			// partial precision
      r3.z = (r1.w * -r1.w) - const_4.y;			// partial precision
      r1.w = (r4.x * r10.x) + (r4.y * r10.y) + (r4.z * r10.z);			// partial precision
      r0.xyz = (r3.z * r5) + r0;			// partial precision
      r3.z = r3.z * r1.w;			// partial precision
      r1.w = (r3.z >= const_2.w ? r3.z : const_2.w);			// partial precision
      r3.w = r3.w - const_4.y;
      r2.xyz = (r1.w * r1) + r2;			// partial precision
    endif
    if_lt const_4.y, r2.w
      r10.xyz = (const_7.x * r3.w) - const_7.yzww;
      r3.x = const_2.w;
      r1 = (r10.x == 0.0 ? LightData[3] : r3.x)
      r1 = (r10.y == 0.0 ? LightData[4] : r1)
      r1 = (r10.z == 0.0 ? LightData[5] : r1)
      r11.xyz = (r10.x == 0.0 ? LightData[2] : r3.x)			// partial precision
      r5.xyz = r1 - input_5;
      r1.xyz = (r10.y == 0.0 ? LightData[3] : r11)			// partial precision
      r11.x = (r9.x * r5.x) + (r9.y * r5.y) + (r9.z * r5.z);
      r11.y = (r8.x * r5.x) + (r8.y * r5.y) + (r8.z * r5.z);
      r11.z = (r7.x * r5.x) + (r7.y * r5.y) + (r7.z * r5.z);
      r1.xyz = (r10.z == 0.0 ? LightData[4] : r1)			// partial precision
      r10.xyz = norm(r11);			// partial precision
      r3.z = (r5.x * r5.x) + (r5.y * r5.y) + (r5.z * r5.z);
      r11.xyz = r6 - r10;			// partial precision
      r3.z = 1.0 / sqrt(r3.z);
      r5.xyz = norm(r11);			// partial precision
      r3.x = 1.0 / r3.z;
      r4.w = sat((r5.x * r4.x) + (r5.y * r4.y) + (r5.z * r4.z));			// partial precision
      r1.w = 1.0 / r1.w;			// partial precision
      pow r3.z, r4.w, ToggleNumLights.z			// partial precision
      r1.w = sat(r3.x * r1.w);
      r5.xyz = r1 * r3.z;			// partial precision
      r3.z = (r1.w * -r1.w) - const_4.y;			// partial precision
      r1.w = (r4.x * r10.x) + (r4.y * r10.y) + (r4.z * r10.z);			// partial precision
      r0.xyz = (r3.z * r5) + r0;			// partial precision
      r3.z = r3.z * r1.w;			// partial precision
      r1.w = (r3.z >= const_2.w ? r3.z : const_2.w);			// partial precision
      r3.w = r3.w - const_4.y;
      r2.xyz = (r1.w * r1) + r2;			// partial precision
    endif
    if_lt const_4.w, r2.w
      r10.xyz = (EyePosition7.x * r3.w) - EyePosition7.yzww;
      r3.x = const_2.w;
      r1 = (r10.x == 0.0 ? LightData[5] : r3.x)
      r1 = (r10.y == 0.0 ? LightData[6] : r1)
      r1 = (r10.z == 0.0 ? LightData[7] : r1)
      r11.xyz = (r10.x == 0.0 ? LightData[4] : r3.x)			// partial precision
      r5.xyz = r1 - input_5;
      r1.xyz = (r10.y == 0.0 ? LightData[5] : r11)			// partial precision
      r11.x = (r9.x * r5.x) + (r9.y * r5.y) + (r9.z * r5.z);
      r11.y = (r8.x * r5.x) + (r8.y * r5.y) + (r8.z * r5.z);
      r11.z = (r7.x * r5.x) + (r7.y * r5.y) + (r7.z * r5.z);
      r1.xyz = (r10.z == 0.0 ? LightData[6] : r1)			// partial precision
      r10.xyz = norm(r11);			// partial precision
      r3.z = (r5.x * r5.x) + (r5.y * r5.y) + (r5.z * r5.z);
      r11.xyz = r6 - r10;			// partial precision
      r3.z = 1.0 / sqrt(r3.z);
      r5.xyz = norm(r11);			// partial precision
      r3.x = 1.0 / r3.z;
      r4.w = sat((r5.x * r4.x) + (r5.y * r4.y) + (r5.z * r4.z));			// partial precision
      r1.w = 1.0 / r1.w;			// partial precision
      pow r3.z, r4.w, ToggleNumLights.z			// partial precision
      r1.w = sat(r3.x * r1.w);
      r5.xyz = r1 * r3.z;			// partial precision
      r3.z = (r1.w * -r1.w) - const_4.y;			// partial precision
      r1.w = (r4.x * r10.x) + (r4.y * r10.y) + (r4.z * r10.z);			// partial precision
      r0.xyz = (r3.z * r5) + r0;			// partial precision
      r3.z = r3.z * r1.w;			// partial precision
      r1.w = (r3.z >= const_2.w ? r3.z : const_2.w);			// partial precision
      r3.w = r3.w - const_4.y;
      r2.xyz = (r1.w * r1) + r2;			// partial precision
    endif
    if_lt -const_7.z, r2.w
      r5.xyz = LightData[7] - input_5;
      r1.x = (r9.x * r5.x) + (r9.y * r5.y) + (r9.z * r5.z);
      r1.y = (r8.x * r5.x) + (r8.y * r5.y) + (r8.z * r5.z);
      r1.z = (r7.x * r5.x) + (r7.y * r5.y) + (r7.z * r5.z);
      r1.w = (r5.x * r5.x) + (r5.y * r5.y) + (r5.z * r5.z);
      r5.xyz = norm(r1);			// partial precision
      r6.xyz = r6 - r5;			// partial precision
      r1.w = 1.0 / sqrt(r1.w);
      r1.w = 1.0 / r1.w;
      r2.w = 1.0 / LightData[7].w;
      r1.xyz = norm(r6);			// partial precision
      r1.w = sat(r1.w * r2.w);
      r3.z = sat((r1.x * r4.x) + (r1.y * r4.y) + (r1.z * r4.z));			// partial precision
      r2.w = (r1.w * -r1.w) - const_4.y;			// partial precision
      pow r1.w, r3.z, ToggleNumLights.z			// partial precision
      r6.xy = (const_8.x * r3.w) - const_8.yzzw;
      r1.x = const_2.w;
      r1.xyz = (r6.x == 0.0 ? LightData[6] : r1.x)			// partial precision
      r3.w = (r4.x * r5.x) + (r4.y * r5.y) + (r4.z * r5.z);			// partial precision
      r1.xyz = (r6.y == 0.0 ? LightData[7] : r1)			// partial precision
      r3.w = r2.w * r3.w;			// partial precision
      r4.xyz = r1.w * r1;			// partial precision
      r1.w = (r3.w >= const_2.w ? r3.w : const_2.w);			// partial precision
      r0.xyz = (r2.w * r4) + r0;			// partial precision
      r2.xyz = (r1.w * r1) + r2;			// partial precision
    endif
    r1.z = r3.y - ToggleADTS.x;			// partial precision
    r1.w = ToggleADTS.x;			// partial precision
    r1.xyz = (r1.w * AmbientColor) + r1.z;			// partial precision
    r1.xyz = r2 - r1;			// partial precision
    r2.xyz = r0.w * r0;			// partial precision
    r0 = BaseMap[r12];			// partial precision
    r0.xyz = r0 * input_1;			// partial precision
    r1.xyz = (r0 * r1) + r2;			// partial precision
    r0.xyz = input_6 - r1;			// partial precision
    rendertarget_0.xyz = (input_6.w * r0) - r1;			// partial precision
    rendertarget_0.w = MatAlpha.x;			// partial precision

// approximately 219 instruction slots used (3 texture, 216 arithmetic)
