//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/STB1000.pso /Fcshaderdump19/STB1000.pso.dis
//
//
// Parameters:
//
//   float4 AmbientColor;
//   sampler2D DiffuseMap;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   AmbientColor const_1       1
//   DiffuseMap   texture_0       1
//

    IN.texcoord_0.xyzw = tex2D(DiffuseMap, IN.texcoord_0.xy);
    r0.xyz = AmbientColor.rgb;
  + r0.w = IN.texcoord_0.w;

// approximately 2 instruction slots used (1 texture, 1 arithmetic)
