//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/STB1005.pso /Fcshaderdump19/STB1005.pso.dis
//
//
// Parameters:
//
//   sampler2D AttMapXY;
//   sampler2D AttMapZ;
//   samplerCUBE NormalCubeMap;
//   sampler2D NormalMap;
//   float4 PSLightColor[4];
//
//
// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   PSLightColor[0]  const_2        1
//   NormalMap     texture_0       1
//   AttMapXY      texture_1       1
//   AttMapZ       texture_2       1
//   NormalCubeMap texture_3       1
//

    IN.texcoord_0 = tex2D(NormalMap, texcoord_0);
    IN.texcoord_1 = tex2D(NormalMap, texcoord_0);
    IN.texcoord_2 = tex2D(NormalMap, texcoord_0);
    IN.texcoord_3 = tex2D(NormalMap, texcoord_0);
    r0.xyz = saturate(dot(2 * ((IN.texcoord_0) - 0.5), 2 * ((IN.texcoord_3) - 0.5)));
    r0.xyz = r0 * PSLightColor[0];
    r1.xyz = IN.texcoord_1 * IN.texcoord_2;
    r0.xyz = r0 * r1;
  + r0.w = PSLightColor[0].a;

// approximately 8 instruction slots used (4 texture, 4 arithmetic)
