//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/GRASS2005.pso /Fcshaderdump19/GRASS2005.pso.dis
//
//
// Parameters:
//
float4 AlphaTestRef : register(c3);
sampler2D AttMap : register(s1);
sampler2D DiffuseMap : register(s0);
float4 PointLightColor : register(c2);
sampler2D ShadowMap : register(s2);
sampler2D ShadowMaskMap : register(s3);
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   PointLightColor const_2       1
//   AlphaTestRef    const_3       1
//   DiffuseMap      texture_0       1
//   AttMap          texture_1       1
//   ShadowMap       texture_2       1
//   ShadowMaskMap   texture_3       1
//


// Structures:

struct VS_OUTPUT {
    float2 DiffuseUV : TEXCOORD0;			// partial precision
    float3 texcoord_4 : TEXCOORD4_centroid;			// partial precision
    float4 texcoord_5 : TEXCOORD5_centroid;			// partial precision
    float4 texcoord_1 : TEXCOORD1;			// partial precision
    float2 texcoord_2 : TEXCOORD2_centroid;			// partial precision
    float3 texcoord_3 : TEXCOORD3_centroid;			// partial precision
    float4 color_0 : COLOR0;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    float1 att0;
    float1 att4;
    float3 q3;
    float3 q5;
    float4 r0;
    float1 t1;
    float3 t2;

    t1.x = tex2D(ShadowMaskMap, IN.texcoord_3.xy);			// partial precision
    t2.xyz = tex2D(ShadowMap, IN.texcoord_2.xy);			// partial precision
    r0.xyzw = tex2D(DiffuseMap, IN.DiffuseUV.xy);			// partial precision
    att4.x = tex2D(AttMap, IN.texcoord_1.zw);			// partial precision
    att0.x = tex2D(AttMap, IN.texcoord_1.xy);			// partial precision
    q3.xyz = (((IN.texcoord_3.z * (t1.x * (t2.xyz - 1))) + 1) * IN.texcoord_5.xyz) + IN.texcoord_4.xyz;			// partial precision
    q5.xyz = (saturate((1 - att0.x) - att4.x) * (0.4 * PointLightColor.rgb)) + q3.xyz;			// partial precision
    OUT.color_0.a = (AlphaTestRef.x >= r0.w ? 0 : IN.texcoord_5.w);			// partial precision
    OUT.color_0.rgb = (r0.xyz * q5.xyz) + ((IN.color_0.rgb - (r0.xyz * q5.xyz)) * IN.color_0.a);			// partial precision

    return OUT;
};

// approximately 24 instruction slots used (5 texture, 19 arithmetic)
