//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/PAR2014.pso /Fcshaderdump19/PAR2014.pso.dis
//
//
// Parameters:
//
float4 AmbientColor;
sampler2D AttenuationMap;
sampler2D BaseMap;
sampler2D NormalMap;
float4 PSLightColor[4];
sampler2D ShadowMap;
sampler2D ShadowMaskMap;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   AmbientColor   const_1       1
//   PSLightColor[0]   const_2        1
//   PSLightColor[1]   const_3        1
//   BaseMap        texture_0       1
//   NormalMap      texture_1       1
//   AttenuationMap texture_4       1
//   ShadowMap      texture_5       1
//   ShadowMaskMap  texture_6       1
//


// Structures:

struct VS_OUTPUT {
    float2 BaseUV : TEXCOORD0;
    float3 texcoord_1 : TEXCOORD1_centroid;
    float3 texcoord_2 : TEXCOORD2_centroid;
    float4 texcoord_4 : TEXCOORD4;
    float3 texcoord_7 : TEXCOORD7_centroid;
    float4 texcoord_6 : TEXCOORD6;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

#define	expand(v)		(((v) - 0.5) / 0.5)
#define	compress(v)		(((v) * 0.5) + 0.5)
#define	uvtile(w)		(((w) * 0.04) - 0.02)
#define	shade(n, l)		max(dot(n, l), 0)
#define	shades(n, l)		saturate(dot(n, l))

    float1 att0;
    float1 att1;
    float3 q10;
    float3 q5;
    float3 q9;
    float4 r0;
    float4 r4;
    float3 t3;
    float1 t4;
    float2 uv8;

    t4.x = tex2D(ShadowMaskMap, IN.texcoord_6.zw);			// partial precision
    t3.xyz = tex2D(ShadowMap, IN.texcoord_6.xy);			// partial precision
    r0.xyzw = tex2D(BaseMap, IN.BaseUV.xy);			// partial precision
    att1.x = tex2D(AttenuationMap, IN.texcoord_4.zw);			// partial precision
    att0.x = tex2D(AttenuationMap, IN.texcoord_4.xy);			// partial precision
    uv8.xy = (uvtile(r0.w) * (IN.texcoord_7.xy / length(IN.texcoord_7.xyz))) + IN.BaseUV.xy;
    r4.xyzw = tex2D(NormalMap, uv8.xy);			// partial precision
    q9.xyz = normalize(expand(r4.xyz));			// partial precision
    q10.xyz = (shades(q9.xyz, normalize(IN.texcoord_2.xyz)) * PSLightColor[1].rgb) * saturate((1 - att0.x) - att1.x);			// partial precision
    q5.xyz = (((t4.x * (t3.xyz - 1)) + 1) * (shades(q9.xyz, IN.texcoord_1.xyz) * PSLightColor[0].rgb)) + q10.xyz;			// partial precision
    OUT.color_0.a = 1;			// partial precision
    OUT.color_0.rgb = q5.xyz + AmbientColor.rgb;			// partial precision

    return OUT;
};

// approximately 36 instruction slots used (6 texture, 30 arithmetic)
