//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SKYSISUN.pso /Fcshaderdump19/SKYSISUN.pso.dis
//


// Structures:

struct VS_OUTPUT {
};

struct PS_OUTPUT {
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    const int4 const_0 = {0, 0, 0, 0};

    OUT.color_0.rgba = 0;

    return OUT;
};

// approximately 1 instruction slot used
