//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SLS1043.pso /Fcshaderdump19/SLS1043.pso.dis
//
//
// Parameters:
//
sampler2D BaseMap : register(s0);
sampler2D GlowMap : register(s1);
float4 PSLightColor[4] : register(c2);
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   PSLightColor[0] const_2        1
//   PSLightColor[1] const_3        1
//   PSLightColor[2] const_4        1
//   BaseMap      texture_0       1
//   GlowMap      texture_1       1
//


// Structures:

struct VS_OUTPUT {
    float2 BaseUV : TEXCOORD0;
    float2 GlowUV : TEXCOORD1;
    float3 texcoord_2 : TEXCOORD2;
    float4 color_0 : COLOR0;
    float4 color_1 : COLOR1;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    float1 q0;
    float4 r0;
    float4 r1;

    r0.xyzw = tex2D(GlowMap, IN.GlowUV.xy);
    r1.xyzw = tex2D(BaseMap, IN.BaseUV.xy);
    q0.x = dot(PSLightColor[1].rgba, IN.color_0.rgba) + dot(PSLightColor[2].rgba, IN.color_1.rgba);
    OUT.color_0.rgb = r0.xyz * (r1.xyz * IN.texcoord_2.xyz);
    OUT.color_0.a = q0.x;

    return OUT;
};

// approximately 8 instruction slots used (2 texture, 6 arithmetic)
