//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SLS2030.pso /Fcshaderdump19/SLS2030.pso.dis
//
//
// Parameters:
//
float4 AmbientColor;
sampler2D AttenuationMap;
sampler2D BaseMap;
float4 EmittanceColor;
sampler2D GlowMap;
sampler2D NormalMap;
float4 PSLightColor[4];
sampler2D ShadowMap;
sampler2D ShadowMaskMap;
//
//
// Registers:
//
//   Name           Reg   Size
//   -------------- ----- ----
//   AmbientColor   const_1       1
//   PSLightColor[0]   const_2        1
//   PSLightColor[1]   const_3        1
//   EmittanceColor const_6       1
//   BaseMap        texture_0       1
//   NormalMap      texture_1       1
//   GlowMap        texture_3       1
//   AttenuationMap texture_4       1
//   ShadowMap      texture_5       1
//   ShadowMaskMap  texture_6       1
//


// Structures:

struct VS_OUTPUT {
    float2 BaseUV : TEXCOORD0;
    float3 texcoord_1 : TEXCOORD1_centroid;
    float3 texcoord_2 : TEXCOORD2_centroid;
    float4 texcoord_4 : TEXCOORD4;
    float4 texcoord_6 : TEXCOORD6;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

#define	expand(v)		(((v) - 0.5) / 0.5)
#define	compress(v)		(((v) * 0.5) + 0.5)
#define	shade(n, l)		max(dot(n, l), 0)
#define	shades(n, l)		saturate(dot(n, l))

    float1 att1;
    float1 att7;
    float3 q3;
    float3 q6;
    float3 q8;
    float4 r0;
    float4 r1;
    float1 r5;
    float4 r6;
    float3 t0;
    float1 t4;

    t4.x = tex2D(ShadowMaskMap, IN.texcoord_6.zw);			// partial precision
    t0.xyz = tex2D(ShadowMap, IN.texcoord_6.xy);			// partial precision
    r6.xyzw = tex2D(NormalMap, IN.BaseUV.xy);			// partial precision
    r1.xyzw = tex2D(GlowMap, IN.BaseUV.xy);
    r0.xyzw = tex2D(BaseMap, IN.BaseUV.xy);			// partial precision
    att7.x = tex2D(AttenuationMap, IN.texcoord_4.zw);			// partial precision
    att1.x = tex2D(AttenuationMap, IN.texcoord_4.xy);			// partial precision
    q6.xyz = normalize(expand(r6.xyz));			// partial precision
    r5.x = shades(q6.xyz, IN.texcoord_1.xyz);			// partial precision
    q8.xyz = saturate((1 - att1.x) - att7.x) * (shades(q6.xyz, normalize(IN.texcoord_2.xyz)) * PSLightColor[1].rgb);			// partial precision
    r0.xyz = (r1.xyz * EmittanceColor.rgb) + AmbientColor.rgb;			// partial precision
    q3.xyz = ((((t4.x * (t0.xyz - 1)) + 1) * (r5.x * PSLightColor[0].rgb)) + q8.xyz) + r0.xyz;			// partial precision
    OUT.color_0.a = r0.w;			// partial precision
    OUT.color_0.rgb = q3.xyz;			// partial precision

    return OUT;
};

// approximately 33 instruction slots used (7 texture, 26 arithmetic)
