//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SLS2039.vso /Fcshaderdump19/SLS2039.vso.dis
//
//
// Parameters:

float4 BoundWorldCenter;
float4 EyePosition;
row_major float4x4 ModelViewProj;
row_major float4x4 ObjToCubeSpace;


// Registers:
//
//   Name             Reg   Size
//   ---------------- ----- ----
//   ModelViewProj[0]    const_0        1
//   ModelViewProj[1]    const_1        1
//   ModelViewProj[2]    const_2        1
//   ModelViewProj[3]    const_3        1
//   ObjToCubeSpace   const_8       4
//   EyePosition      const_25      1
//   BoundWorldCenter const_46      1
//



// Structures:

struct VS_INPUT {
    float4 position : POSITION;
    float4 texcoord_0 : TEXCOORD0;
    float4 color_0 : COLOR0;
};

struct VS_OUTPUT {
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

    const int4 const_4 = {1, -2, 3, 0};
    const float4 const_5 = {0.5, -0.8, 6.66666651, 0};

    OUT.color_0.rgb = IN.color_0;
    OUT.position.w = dot(ModelViewProj[3].xyzw, IN.position.xyzw);
    OUT.position.x = dot(ModelViewProj[0].xyzw, IN.position.xyzw);
    OUT.position.y = dot(ModelViewProj[1].xyzw, IN.position.xyzw);
    OUT.position.z = dot(ModelViewProj[2].xyzw, IN.position.xyzw);
    OUT.texcoord_0.xy = IN.texcoord_0;
    OUT.texcoord_1.xyz = (0.5 * r1) + 0.5;
    r0.xyzw = r1 - BoundWorldCenter;
    r0.w = dot(r0.xyzw, r0.xyzw);	// normalize + length
    r0.w = 1.0 / sqrt(r0.w);
    r1.x = dot(ObjToCubeSpace.xyzw, IN.position.xyzw);
    r1.y = dot(const_9.xyzw, IN.position.xyzw);
    r1.z = dot(const_10.xyzw, IN.position.xyzw);
    r2.xyz = EyePosition.xyz - r1.xyz;
    r1.xyz = r0.xyz * r0.w;
    r3.x = dot(r1.xyz, r1.xyz);	// normalize + length
    r0.w = 1.0 / sqrt(r3.x);
    r0.xyz = normalize(r2);
    OUT.texcoord_2.xyz = r0.xyz;
    r2.x = dot(r1.xyz, r0.xyz);
    r0.w = (r2.x * r0.w) + -0.8;
    r0.w = r0.w * 6.66666651;
    r0.w = max(r0.w, 0);
    r1.w = dot(const_11.xyzw, IN.position.xyzw);
    r1.w = min(r0.w, 1);
    r0.w = (r1.w * -2) + 3;
    r1.w = r1.w * r1.w;
    OUT.texcoord_1.w = r0.w * r1.w;

    return OUT;
};

// approximately 30 instruction slots used
