//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/SLS2064.pso /Fcshaderdump19/SLS2064.pso.dis
//
//
// Parameters:
//
sampler2D NormalMap;
float PSRefractionPower;
//
//
// Registers:
//
//   Name              Reg   Size
//   ----------------- ----- ----
//   PSRefractionPower const_25      1
//   NormalMap         texture_0       1
//


// Structures:

struct VS_OUTPUT {
    float4 NormalUV : TEXCOORD0;			// partial precision
    float texcoord_1 : TEXCOORD1;			// partial precision
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

#define	expand(v)		(((v) - 0.5) / 0.5)
#define	compress(v)		(((v) * 0.5) + 0.5)
#define	weight(v)		dot(v, 1)
#define	sqr(v)			((v) * (v))

    float4 r0;

    r0.xyzw = tex2D(NormalMap, IN.NormalUV.xy);
    r0.xy = compress(normalize(expand(r0.xy)) / IN.NormalUV.w);			// partial precision	// [-1,+1] to [0,1]
    r0.z = PSRefractionPower.x;			// partial precision
    OUT.color_0.a = sqr(IN.texcoord_1.x) * 0.5;			// partial precision
    OUT.color_0.rgb = r0.xyz;			// partial precision

    return OUT;
};

// approximately 13 instruction slots used (1 texture, 12 arithmetic)
