//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/SM3LL004.pso /Fcshaderdump19/SM3LL004.pso.dis
//
//
// Parameters:

float4 AmbientColor;
sampler2D BaseMap;
float3 EyePosition;
float4 LightData[8];
float3 MatAlpha;
sampler2D NormalMap;
float4 ToggleADTS;
float4 ToggleNumLights;


// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   AmbientColor    const_0       1
//   EyePosition     const_1       1
//   MatAlpha        const_3       1
//   ToggleADTS      const_5       1
//   ToggleNumLights const_6       1
//   LightData[0]       const_9        1
//   LightData[1]       const_10        1
//   LightData[2]       const_11        1
//   LightData[3]       const_12        1
//   LightData[4]       const_13        1
//   LightData[5]       const_14        1
//   LightData[6]       const_15        1
//   LightData[7]       const_16        1
//   BaseMap         texture_0       1
//   NormalMap       texture_1       1
//



// Structures:

struct VS_OUTPUT {
    float2 texcoord_0 : TEXCOORD0;			// partial precision
    float3 color_0 : COLOR0;			// partial precision
    float3 input_2 : TEXCOORD3_centroid;			// partial precision
    float3 input_3 : TEXCOORD4_centroid;			// partial precision
    float3 input_4 : TEXCOORD5_centroid;			// partial precision
    float3 input_5 : TEXCOORD6_centroid;			// partial precision
    float4 input_6 : TEXCOORD7_centroid;			// partial precision
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

#define	PI	3.14159274
#define	D3DSINCOSCONST1	-1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
#define	D3DSINCOSCONST2	-0.020833334, -0.125, 1, 0.5

    const float4 const_2 = {0.04, -0.02, -0.5, 0};
    const int4 const_4 = {1, 4, 0, 2};
    const int4 const_7 = {2, -6, -7, 0};
    const int4 const_8 = {2, -4, -5, -6};
    const int4 const_17 = {2, -2, -3, -4};

    float4 r0;
    float4 r1;
    float2 r10;
    float4 r2;
    float4 r3;
    float4 r4;
    float3 r5;
    float3 r6;
    float3 r7;
    float3 r8;
    float2 r9;

    r0.xyzw = tex2D(BaseMap, IN.texcoord_0.xy);			// partial precision
    r9.xy = const_4.xy;
    r3.z = min(ToggleNumLights.y, r9.y - ToggleNumLights.x);			// partial precision
    r1.w = frac(r3.z);			// partial precision
    r1.xyz = EyePosition.xyz - IN.input_5.xyz;			// partial precision
    r4.xyz = normalize(IN.input_4.xyz);			// partial precision
    r0.z = dot(r4.xyz, r1.xyz);			// partial precision
    r6.xyz = normalize(IN.input_2.xyz);			// partial precision
    r0.x = dot(r6.xyz, r1.xyz);			// partial precision
    r5.xyz = normalize(IN.input_3.xyz);			// partial precision
    r0.y = dot(r5.xyz, r1.xyz);			// partial precision
    r1.z = dot(r4.xyz, LightData[1].xyz);			// partial precision
    r10.xy = (((r0.w * 0.04) - 0.02) * (r0.xy / length(r0.xyz))) + IN.texcoord_0.xy;			// partial precision
    r0.xyzw = tex2D(NormalMap, r10.xy);
    r2.xyz = normalize(2 * (r0.xyz - 0.5));			// partial precision	// [0,1] to [-1,+1]
    r0.w = 1;
    r1.x = dot(r6.xyz, LightData[1].xyz);			// partial precision
    r1.y = dot(r5.xyz, LightData[1].xyz);			// partial precision
    r3.w = ((r3.z >= 0.0 ? 1 : 0) * (r1.w <= 0.0 ? 1 : 0)) + (r3.z - r1.w);
    r1.w = (r3.w <= 0.0 ? 1 : 0);
    r2.w = 0;
    r0.xyz = max(dot(r2.xyz, r1.xyz), 0) * LightData[0].xyz;			// partial precision
    r0.xyzw = (ToggleNumLights.x <= 0.0 ? r0.xyzw : r2.w);
    if_ne 0, r1.w
      r3.yz = (2 * r0.w) - const_4.xx;
      r3.xyz = (r1 >= 0.0 ? -r3.xyz : ((2 * r0.w) - const_4.zxw));
      r1.xyzw = (r3.z <= 0.0 ? ((r3.y <= 0.0 ? (r3.x <= 0.0 ? r2.w : LightData[1].xyzw) : LightData[2].xyzw)) : LightData[3].xyzw);
      r7.xyz = r1.xyz - IN.input_5.xyz;
      r1.xyz = (r3.x <= 0.0 ? r2.w : LightData[0].xyz);			// partial precision
      r4.w = 1.0 / length(r7.xyz);
      r3.x = saturate((1.0 / r4.w) / r1.w);
      r3.x = 1.0 - (r3.x * r3.x);			// partial precision
      r1.xyz = (r3.y <= 0.0 ? r1.xyz : LightData[1].xyz);			// partial precision
      r8.x = dot(r6.xyz, r7.xyz);
      r8.y = dot(r5.xyz, r7.xyz);
      r8.z = dot(r4.xyz, r7.xyz);
      r7.xyz = normalize(r8.xyz);			// partial precision
      r3.y = dot(r2.xyz, r7.xyz) * r3.x;			// partial precision
      r1.xyz = (r3.z <= 0.0 ? r1.xyz : LightData[2].xyz);			// partial precision
      r1.w = max(r3.y, 0);			// partial precision
      r0.xyz = (r1.w * r1.xyz) + r0.xyz;			// partial precision
      r0.w = r0.w + 1;
    endif
    if_lt 1, r3.w
      r3.xyz = (2 * r0.w) + const_17.yzw;
      r1.xyzw = (r3.z == 0.0 ? LightData[5].xyzw : ((r3.y == 0.0 ? LightData[4].xyzw : (r3.x == 0.0 ? LightData[3].xyzw : r2.w))));
      r7.xyz = r1.xyz - IN.input_5.xyz;
      r1.xyz = (r3.x == 0.0 ? LightData[2].xyz : r2.w);			// partial precision
      r4.w = 1.0 / length(r7.xyz);
      r3.x = saturate((1.0 / r4.w) / r1.w);
      r1.xyz = (r3.z == 0.0 ? LightData[4].xyz : (r3.y == 0.0 ? LightData[3].xyz : r1.xyz));			// partial precision
      r8.x = dot(r6.xyz, r7.xyz);
      r8.y = dot(r5.xyz, r7.xyz);
      r8.z = dot(r4.xyz, r7.xyz);
      r7.xyz = normalize(r8.xyz);			// partial precision
      r3.xyz = (max(dot(r2.xyz, r7.xyz) * (1.0 - (r3.x * r3.x)), 0) * r1.xyz) + r0.xyz;			// partial precision
      r1.w = r0.w + 1;
    else
      r1.w = r0.w;
      r3.xyz = r0.xyz;			// partial precision
    endif
    if_lt 2, r3.w
      r1.xyz = (2 * r1.w) + const_8.yzw;
      r0.xyzw = (r1.z == 0.0 ? LightData[7].xyzw : ((r1.y == 0.0 ? LightData[6].xyzw : (r1.x == 0.0 ? LightData[5].xyzw : r2.w))));
      r7.xyz = r0.xyz - IN.input_5.xyz;
      r0.xyz = (r1.x == 0.0 ? LightData[4].xyz : r2.w);			// partial precision
      r4.w = 1.0 / length(r7.xyz);
      r1.x = saturate((1.0 / r4.w) / r0.w);
      r1.x = 1.0 - (r1.x * r1.x);			// partial precision
      r0.xyz = (r1.y == 0.0 ? LightData[5].xyz : r0.xyz);			// partial precision
      r8.x = dot(r6.xyz, r7.xyz);
      r8.y = dot(r5.xyz, r7.xyz);
      r8.z = dot(r4.xyz, r7.xyz);
      r7.xyz = normalize(r8.xyz);			// partial precision
      r1.y = dot(r2.xyz, r7.xyz) * r1.x;			// partial precision
      r0.xyz = (r1.z == 0.0 ? LightData[6].xyz : r0.xyz);			// partial precision
      r0.w = max(r1.y, 0);			// partial precision
      r1.w = r1.w + 1;
      r3.xyz = (r0.w * r0.xyz) + r3.xyz;			// partial precision
    endif
    if_lt 3, r3.w
      r0.xyz = LightData[7].xyz - IN.input_5.xyz;
      r1.x = dot(r6.xyz, r0.xyz);
      r1.y = dot(r5.xyz, r0.xyz);
      r1.z = dot(r4.xyz, r0.xyz);
      r0.w = dot(r0.xyz, r0.xyz);	// normalize + length
      r0.xyz = normalize(r1.xyz);			// partial precision
      r1.z = sqrt(r0.w);
      r0.w = dot(r2.xyz, r0.xyz);			// partial precision
      r0.z = saturate(r1.z / LightData[7].w);
      r1.xy = (2 * r1.w) + const_7.yz;
      r1.w = r0.w * (1.0 - (r0.z * r0.z));			// partial precision
      r0.w = max(r1.w, 0);			// partial precision
      r0.xyz = (r1.y == 0.0 ? LightData[7].xyz : (r1.x == 0.0 ? LightData[6].xyz : r2.w));			// partial precision
      r3.xyz = (r0.w * r0.xyz) + r3.xyz;			// partial precision
    endif
    r0.xyzw = tex2D(BaseMap, r10.xy);			// partial precision
    r1.xyz = (r0.xyz * IN.color_0.rgb) * (r3.xyz + ((ToggleADTS.x * AmbientColor.rgb) + (r9.x - ToggleADTS.x)));			// partial precision
    OUT.color_0.rgb = (IN.input_6.w * (IN.input_6.xyz - r1.xyz)) + r1.xyz;			// partial precision
    OUT.color_0.a = MatAlpha.x;			// partial precision

    return OUT;
};

// approximately 162 instruction slots used (3 texture, 159 arithmetic)
