//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/STFROND001.vso /Fcshaderdump19/STFROND001.vso.dis
//
//
// Parameters:

float4 AmbientColor;
float4 DiffColor;
float3 FogColor;
float4 FogParam;
float4 LightVector;
row_major float4x4 ModelViewProj;
float SunDimmer;
float4 WindMatrices[16];


// Registers:
//
//   Name          Reg   Size
//   ------------- ----- ----
//   ModelViewProj[0] const_0        1
//   ModelViewProj[1] const_1        1
//   ModelViewProj[2] const_2        1
//   ModelViewProj[3] const_3        1
//   AmbientColor  const_5       1
//   DiffColor     const_6       1
//   LightVector   const_8       1
//   FogParam      const_14      1
//   FogColor      const_15      1
//   SunDimmer     const_16      1
//   WindMatrices[0]  const_18      4
//   WindMatrices[1]  const_19      4
//   WindMatrices[2]  const_20      4
//   WindMatrices[3]  const_21      4
//



// Structures:

struct VS_INPUT {
    float4 position : POSITION;
    float3 normal : NORMAL;
    float4 texcoord_0 : TEXCOORD0;
    float4 color_0 : COLOR0;
    float4 blendindices : BLENDINDICES;
};

struct VS_OUTPUT {
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

    const int4 const_4 = {0, 1, 0, 0};

    OUT.texcoord_0.xy = IN.texcoord_0;
    OUT.texcoord_2.xyz = FogColor.rgb;
    offset.x = IN.blendindices.y;
    r0.w = dot(WindMatrices[3 + offset.x].xyzw, IN.position.xyzw);
    r0.x = dot(WindMatrices[0 + offset.x].xyzw, IN.position.xyzw);
    r0.y = dot(WindMatrices[1 + offset.x].xyzw, IN.position.xyzw);
    r0.z = dot(WindMatrices[2 + offset.x].xyzw, IN.position.xyzw);
    r0.xyzw = r0 - IN.position;
    r0.xyzw = (IN.blendindices.x * r0) + r1;
    OUT.position.w = dot(ModelViewProj[3].xyzw, r0.xyzw);
    r1.xyzw = IN.position;
    r2.x = dot(IN.normal.xyz, LightVector.xyz);
    r1.w = max(r2.x, 0);
    r2.w = min(r1.w, 1);
    r1.w = 1.0 / FogParam.y;
    r1.x = dot(ModelViewProj[0].xyzw, r0.xyzw);
    r1.y = dot(ModelViewProj[1].xyzw, r0.xyzw);
    r1.z = dot(ModelViewProj[2].xyzw, r0.xyzw);
    OUT.position.xyz = r1.xyz;
    r0.x = dot(r1.xyz, r1.xyz);	// normalize + length
    r0.w = 1.0 / sqrt(r0.x);
    r0.w = 1.0 / r0.w;
    r0.w = FogParam.x - r0.w;
    r0.w = r0.w * r1.w;
    r0.w = max(r0.w, 0);
    r0.w = min(r0.w, 1);
    OUT.texcoord_2.w = 1 - r0.w;
    r0.xyz = r2.w * DiffColor.rgb;
    r1.w = SunDimmer.x;
    r0.xyz = (r1.w * r0.xyz) + AmbientColor.rgb;
    OUT.texcoord_1.xyz = r0.xyz * IN.color_0;

    return OUT;
};

// approximately 31 instruction slots used
