//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/WATERDISPLACE004.pso
//    /Fcshaderdump19/WATERDISPLACE004.pso.dis
//
//
// Parameters:

sampler2D HeightMap;


// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   HeightMap    texture_0       1
//



// Structures:

struct VS_OUTPUT {
    float2 texcoord_0 : TEXCOORD0;
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

#define	PI	3.14159274
#define	D3DSINCOSCONST1	-1.55009923e-006, -2.17013894e-005, 0.00260416674, 0.00026041668
#define	D3DSINCOSCONST2	-0.020833334, -0.125, 1, 0.5

    const float4 const_0 = {0, -(1.0 / 256), 2, -1};
    const float4 const_1 = {0.125, 0.5, 0, 0};
    const float4 const_2 = {-(1.0 / 256), 0, -3, 0};


    OUT.color_0.rgba = (0.125 * (((2 * (tex2D(HeightMap, IN.texcoord_0.xy - const_2.xy))) + ((2 * (tex2D(HeightMap, IN.texcoord_0.xy + const_2.xy))) + ((2 * (tex2D(HeightMap, IN.texcoord_0.xy - const_0.xy))) + ((2 * (tex2D(HeightMap, IN.texcoord_0.xy + const_0.xy))) - 1)))) - 3)) + 0.5;

    return OUT;
};

// approximately 15 instruction slots used (4 texture, 11 arithmetic)
