//
// Generated by Microsoft (R) D3DX9 Shader Compiler 5.04.00.2904
//
//   fxc /Tps_2_b HLSL/BOLT.p.hlsl /FcHLSL/BOLT.p.asm
//
//
// Parameters:
//
//   float4 CoreColor;
//   float4 GlowColor;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   CoreColor    c0       1
//   GlowColor    c1       1
//

    ps_2_x
    def c2, 1, 0, 0, 0
    dcl v0
    dcl t0.x
    add r0.w, -t0.x, c2.x
    add r1.w, t0.x, c2.x
    cmp r1.w, -t0.x, r0.w, r1.w
    mul r0.w, r1.w, r1.w
    mul r0.w, r0.w, r0.w
    mul r0.w, r1.w, r0.w
    mul r0.xyz, r1.w, c1
    mad r0.xyz, c0, r0.w, r0
    mov r0.w, v0.w
    mov oC0, r0

// approximately 10 instruction slots used
