//
// Generated by Microsoft (R) D3DX9 Shader Compiler 5.04.00.2904
//
//   fxc /Tps_2_b HLSL/HDR000.p.hlsl /FcHLSL/HDR000.p.asm
//
//
// Parameters:
//
//   float4 BlurOffsets[16];
//   float2 BlurScale;
//   sampler2D Src0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   BlurOffsets  c0       4
//   BlurScale    c4       1
//   Src0         s0       1
//

    ps_2_x
    def c5, 1, 0, 0, 0
    dcl t0.xy
    dcl_2d s0
    mov r0.xy, c4
    mad r3.xy, c0, r0, t0
    mad r2.xy, c1, r0, t0
    mad r1.xy, c2, r0, t0
    mad r0.xy, c3, r0, t0
    texld r3, r3, s0
    texld r2, r2, s0
    texld r1, r1, s0
    texld r0, r0, s0
    mul r3.xyz, r3, c0.z
    mad r2.xyz, c1.z, r2, r3
    mad r1.xyz, c2.z, r1, r2
    mad r0.xyz, c3.z, r0, r1
    mov r0.w, c5.x
    mov oC0, r0

// approximately 15 instruction slots used (4 texture, 11 arithmetic)
