//
// Generated by Microsoft (R) D3DX9 Shader Compiler 5.04.00.2904
//
//   fxc /Tps_2_b HLSL/MAP000.p.hlsl /FcHLSL/MAP000.p.asm
//
//
// Parameters:
//
//   float4 CameraPos;
//   sampler2D Src0;
//   sampler2D Src1;
//   sampler2D Src2;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   CameraPos    c0       1
//   Src0         s0       1
//   Src1         s1       1
//   Src2         s2       1
//

    ps_2_x
    def c1, 1, -1, 10, 0.100000001
    def c2, 0.200000003, 0.200000003, 0.150000006, 0.5
    def c3, 0.458999991, 0.231000006, 0.128999993, 0
    def c4, -0.458999991, -0.231000006, -0.128999993, 0
    def c5, 0.25, 0.75, 0, 0
    def c6, -1, 1, 2, -2
    dcl t0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    mov r3.x, t0.x
    mov r0.xy, c0
    mad r5.xy, r0, c6, t0
    mov r3.y, r5.y
    mov r7.x, t0.x
    add r6.xy, t0, -c0
    mov r7.y, r6.y
    mov r1.x, r6.x
    mad r4.xy, r0, c1, t0
    mov r0.x, r4.x
    add r2.xy, t0, c0
    mov r1.y, t0.y
    mov r0.y, t0.y
    texld r5, r5, s0
    texld r3, r3, s0
    texld r9, r7, s0
    texld r8, r6, s0
    texld r6, r4, s0
    texld r4, r2, s0
    texld r7, r1, s0
    texld r2, r0, s0
    texld r1, t0, s1
    texld r0, t0, s2
    mad r9, c6.z, r9, r8
    add r9, r6, r9
    add r9, -r5, r9
    mad r3, r3, c6.w, r9
    add r3, -r4, r3
    mul r3, r3, r3
    mad r7, c6.z, r7, r8
    add r5, r5, r7
    add r5, -r6, r5
    mad r2, r2, c6.w, r5
    add r2, -r4, r2
    mad r2, r2, r2, r3
    mul r1.w, r2.w, c1.z
    dp3 r2.x, c2, r2
    min r0.w, r1.w, c1.w
    mul r1.xyz, r1, c5.x
    add r1.w, r2.x, r0.w
    mad r0.xyz, r0, c5.y, r1
    min r0.w, r1.w, c2.w
    add r0.xyz, r0, c4
    mad r0.xyz, r0.w, r0, c3
    mov r0.w, c6.y
    mov oC0, r0

// approximately 46 instruction slots used (10 texture, 36 arithmetic)
