//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   psa shaderdump19/STLEAF2000.pso /Fcshaderdump19/STLEAF2000.pso.dis
//
//
// Parameters:

sampler2D DiffuseMap;

// Structures:

struct VS_OUTPUT {
    float2 texcoord_0 : TEXCOORD0;				// partial precision
    float3 ilum : TEXCOORD1;					// partial precision
};

struct PS_OUTPUT {
    float4 color_0 : COLOR0;
};

// Code:

PS_OUTPUT main(VS_OUTPUT IN) {
    PS_OUTPUT OUT;

    float4 r0 = tex2D(DiffuseMap, IN.texcoord_0);		// partial precision
    float3 r1 = IN.ilum;					// partial precision

    OUT.color_0.rgb = r0.rgb * r1;				// partial precision
    OUT.color_0.a = r0.a;					// partial precision

    return OUT;
};

// approximately 3 instruction slots used (1 texture, 2 arithmetic)
