//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.08.299.0000
//
//   vsa shaderdump19/WATERDISPLACE001.vso
//    /Fcshaderdump19/WATERDISPLACE001.vso.dis
//
//
// Parameters:

float4 texRatio0;

// Structures:

struct VS_INPUT {
    float4 position : POSITION;
    float4 texcoord_0 : TEXCOORD0;
};

struct VS_OUTPUT {
    float4 position : POSITION;
    float2 texcoord_0 : TEXCOORD0;
};

// Code:

VS_OUTPUT main(VS_INPUT IN) {
    VS_OUTPUT OUT;

    OUT.position.xy = (IN.position * texRatio0) + texRatio0.zwzw;
    OUT.position.zw = IN.position;
    OUT.texcoord_0.xy = IN.texcoord_0;

    return OUT;
};

// approximately 3 instruction slots used
